import type { SeedTransaction } from "../types";

export const transactions028: SeedTransaction[] = [
  {
    id: "txn_000274",
    source: "initial_excel_import",
    sourceRow: 266,
    date: "2024-09-26",
    action: "Cash Dividend",
    assetTicker: "ASX:AIZ",
    quantity: 1,
    price: 16.35,
    fees: 0,
    currency: "AUD",
    platform: "CDIA - Dividends",
    assetClass: "Stock",
    sector: "Others",
    country: "Australia",
    strategy: "Dividend",
    notes: null
  },
  {
    id: "txn_000275",
    source: "initial_excel_import",
    sourceRow: 267,
    date: "2024-09-27",
    action: "Cash Dividend",
    assetTicker: "ASX:FMG",
    quantity: 1,
    price: 94.34,
    fees: 0,
    currency: "AUD",
    platform: "CDIA - Dividends",
    assetClass: "Stock",
    sector: "Materials",
    country: "Australia",
    strategy: "Dividend",
    notes: null
  },
  {
    id: "txn_000276",
    source: "initial_excel_import",
    sourceRow: 268,
    date: "2024-09-27",
    action: "Cash Dividend",
    assetTicker: "NYSE:LMT",
    quantity: 1,
    price: 3.15,
    fees: 0,
    currency: "AUD",
    platform: "CDIA - Dividends",
    assetClass: "Cash",
    sector: "Others",
    country: "Australia",
    strategy: "Dividend",
    notes: null
  },
  {
    id: "txn_000277",
    source: "initial_excel_import",
    sourceRow: 269,
    date: "2024-10-01",
    action: "Cash Interest",
    assetTicker: "Interest",
    quantity: 1,
    price: 0.06,
    fees: 0,
    currency: "AUD",
    platform: "CDIA - Dividends",
    assetClass: "Cash",
    sector: "Others",
    country: "Australia",
    strategy: "Dividend",
    notes: null
  },
  {
    id: "txn_000278",
    source: "initial_excel_import",
    sourceRow: 270,
    date: "2024-10-03",
    action: "Cash Dividend",
    assetTicker: "ASX:WDS",
    quantity: 1,
    price: 35.70,
    fees: 0,
    currency: "AUD",
    platform: "CDIA - Dividends",
    assetClass: "Stock",
    sector: "Energy",
    country: "Australia",
    strategy: "Dividend",
    notes: null
  },
  {
    id: "txn_000279",
    source: "initial_excel_import",
    sourceRow: 271,
    date: "2024-10-10",
    action: "Cash Dividend",
    assetTicker: "ASX:COH",
    quantity: 1,
    price: 4.20,
    fees: 0,
    currency: "AUD",
    platform: "CDIA - Dividends",
    assetClass: "Stock",
    sector: "Healthcare",
    country: "Australia",
    strategy: "Dividend",
    notes: null
  },
  {
    id: "txn_000280",
    source: "initial_excel_import",
    sourceRow: 272,
    date: "2024-10-10",
    action: "Cash Dividend",
    assetTicker: "ASX:EDV",
    quantity: 1,
    price: 11.33,
    fees: 0,
    currency: "AUD",
    platform: "CDIA - Dividends",
    assetClass: "Stock",
    sector: "Consumer Staples",
    country: "Australia",
    strategy: "Dividend",
    notes: null
  },
  {
    id: "txn_000281",
    source: "initial_excel_import",
    sourceRow: 273,
    date: "2024-10-14",
    action: "Cash Deposit",
    assetTicker: "Cash",
    quantity: 1,
    price: 125.00,
    fees: 0,
    currency: "AUD",
    platform: "Commsec Bank",
    assetClass: "Cash",
    notes: "Kieren Chan"
  },
  {
    id: "txn_000282",
    source: "initial_excel_import",
    sourceRow: 274,
    date: "2024-10-15",
    action: "Cash Deposit",
    assetTicker: "Cash",
    quantity: 1,
    price: 125.00,
    fees: 0,
    currency: "AUD",
    platform: "Commsec Bank",
    assetClass: "Cash",
    notes: "Sam Thomas"
  },
  {
    id: "txn_000283",
    source: "initial_excel_import",
    sourceRow: 275,
    date: "2024-10-16",
    action: "Cash Dividend",
    assetTicker: "VAS.AX",
    quantity: 1,
    price: 4.21,
    fees: 0,
    currency: "AUD",
    platform: "CDIA - Dividends",
    assetClass: "ETF",
    sector: "ETF",
    country: "Australia",
    strategy: "Dividend",
    notes: null
  }
];
