import type { SeedTransaction } from "../types";

export const transactions038: SeedTransaction[] = [
  {
    id: "txn_000374",
    source: "initial_excel_import",
    sourceRow: 366,
    date: "2025-08-14",
    action: "Cash Deposit",
    assetTicker: "Cash",
    quantity: 1,
    price: 2831.48,
    fees: 0,
    currency: "AUD",
    platform: "Commsec Bank",
    assetClass: "Cash",
    notes: "BNB AND ETH 14/08/2025"
  },
  {
    id: "txn_000375",
    source: "initial_excel_import",
    sourceRow: 367,
    date: "2025-08-14",
    action: "Cash Withdrawal",
    assetTicker: "Cash",
    quantity: 1,
    price: 800.00,
    fees: 0,
    currency: "AUD",
    platform: "Commsec Bank",
    assetClass: "Cash",
    notes: "Invest ALB"
  },
  {
    id: "txn_000376",
    source: "initial_excel_import",
    sourceRow: 368,
    date: "2025-08-15",
    action: "Buy",
    assetTicker: "ASX:IEL",
    quantity: 180,
    price: 4.458,
    fees: 4.99,
    currency: "AUD",
    platform: "Commsec Shares",
    assetClass: "Stock",
    sector: "Consumer Discretionary",
    country: "Australia",
    strategy: "High Risk",
    notes: "Sam Selected"
  },
  {
    id: "txn_000377",
    source: "initial_excel_import",
    sourceRow: 369,
    date: "2025-08-15",
    action: "Buy",
    assetTicker: "ASX:NDQ",
    quantity: 15,
    price: 54.01,
    fees: 4.99,
    currency: "AUD",
    platform: "Commsec Shares",
    assetClass: "ETF",
    sector: "ETF",
    country: "Australia",
    strategy: "Low Risk",
    notes: "Tom Selected"
  },
  {
    id: "txn_000378",
    source: "initial_excel_import",
    sourceRow: 370,
    date: "2025-08-15",
    action: "Buy",
    assetTicker: "ASX:EDV",
    quantity: 120,
    price: 4.185,
    fees: 4.99,
    currency: "AUD",
    platform: "Commsec Shares",
    assetClass: "Stock",
    sector: "Consumer Staples",
    country: "Australia",
    strategy: "Dividend",
    notes: "Tom Selected"
  },
  {
    id: "txn_000379",
    source: "initial_excel_import",
    sourceRow: 371,
    date: "2025-08-15",
    action: "Buy",
    assetTicker: "ASX:NAB",
    quantity: 13,
    price: 39.14,
    fees: 4.99,
    currency: "AUD",
    platform: "Commsec Shares",
    assetClass: "Stock",
    sector: "Financials",
    country: "Australia",
    strategy: "Low Risk",
    notes: "Kieren Selected"
  },
  {
    id: "txn_000380",
    source: "initial_excel_import",
    sourceRow: 372,
    date: "2025-08-15",
    action: "Buy",
    assetTicker: "ASX:GMG",
    quantity: 14,
    price: 36.00,
    fees: 4.99,
    currency: "AUD",
    platform: "Commsec Shares",
    assetClass: "Stock",
    sector: "Real Estate",
    country: "Australia",
    strategy: "Dividend",
    notes: "Sam Selected"
  },
  {
    id: "txn_000381",
    source: "initial_excel_import",
    sourceRow: 373,
    date: "2025-08-15",
    action: "Cash Withdrawal",
    assetTicker: "Cash",
    quantity: 1,
    price: 0,
    fees: 0,
    currency: "AUD",
    platform: "Commsec Bank",
    assetClass: "Cash",
    notes: null
  },
  {
    id: "txn_000382",
    source: "initial_excel_import",
    sourceRow: 374,
    date: "2025-08-15",
    action: "Cash Deposit",
    assetTicker: "Cash",
    quantity: 1,
    price: 150,
    fees: 0,
    currency: "AUD",
    platform: "Commsec Bank",
    assetClass: "Cash",
    notes: "Sam Thomas"
  },
  {
    id: "txn_000383",
    source: "initial_excel_import",
    sourceRow: 375,
    date: "2025-08-17",
    action: "Cash Deposit",
    assetTicker: "Cash",
    quantity: 1,
    price: 150,
    fees: 0,
    currency: "AUD",
    platform: "Commsec Bank",
    assetClass: "Cash",
    notes: "Tom Flitcroft"
  }
];
