import type { SeedTransaction } from "../types";

export const transactions029: SeedTransaction[] = [
  {
    id: "txn_000284",
    source: "initial_excel_import",
    sourceRow: 276,
    date: "2024-10-18",
    action: "Cash Deposit",
    assetTicker: "Cash",
    quantity: 1,
    price: 125.00,
    fees: 0,
    currency: "AUD",
    platform: "Commsec Bank",
    assetClass: "Cash",
    notes: "Tom Flitcroft"
  },
  {
    id: "txn_000285",
    source: "initial_excel_import",
    sourceRow: 277,
    date: "2024-11-01",
    action: "Cash Interest",
    assetTicker: "Interest",
    quantity: 1,
    price: 0.11,
    fees: 0,
    currency: "AUD",
    platform: "CDIA - Dividends",
    assetClass: "Cash",
    sector: "Others",
    country: "Australia",
    strategy: "Dividend",
    notes: null
  },
  {
    id: "txn_000286",
    source: "initial_excel_import",
    sourceRow: 278,
    date: "2024-11-13",
    action: "Cash Deposit",
    assetTicker: "Cash",
    quantity: 1,
    price: 125.00,
    fees: 0,
    currency: "AUD",
    platform: "Commsec Bank",
    assetClass: "Cash",
    notes: "Sam Thomas"
  },
  {
    id: "txn_000287",
    source: "initial_excel_import",
    sourceRow: 279,
    date: "2024-11-14",
    action: "Cash Deposit",
    assetTicker: "Cash",
    quantity: 1,
    price: 625.00,
    fees: 0,
    currency: "AUD",
    platform: "Commsec Bank",
    assetClass: "Cash",
    notes: "Marc Mario"
  },
  {
    id: "txn_000288",
    source: "initial_excel_import",
    sourceRow: 280,
    date: "2024-11-18",
    action: "Cash Deposit",
    assetTicker: "Cash",
    quantity: 1,
    price: 125.00,
    fees: 0,
    currency: "AUD",
    platform: "Commsec Bank",
    assetClass: "Cash",
    notes: "Tom Flitcroft"
  },
  {
    id: "txn_000289",
    source: "initial_excel_import",
    sourceRow: 281,
    date: "2024-11-22",
    action: "Cash Deposit",
    assetTicker: "Cash",
    quantity: 1,
    price: 125.00,
    fees: 0,
    currency: "AUD",
    platform: "Commsec Bank",
    assetClass: "Cash",
    notes: "Kieren Chan"
  },
  {
    id: "txn_000290",
    source: "initial_excel_import",
    sourceRow: 282,
    date: "2024-11-27",
    action: "Buy",
    assetTicker: "VAS.AX",
    quantity: 5,
    price: 104.51,
    fees: 4.99,
    currency: "AUD",
    platform: "Commsec Shares",
    assetClass: "ETF",
    sector: "ETF",
    country: "Australia",
    strategy: "Low Risk",
    notes: null
  },
  {
    id: "txn_000291",
    source: "initial_excel_import",
    sourceRow: 283,
    date: "2024-11-27",
    action: "Transfer Send",
    assetTicker: "Cash",
    quantity: 1,
    price: 400.00,
    fees: 0,
    currency: "AUD",
    platform: "Commsec Shares",
    assetClass: "Cash",
    notes: "ASX Shares"
  },
  {
    id: "txn_000292",
    source: "initial_excel_import",
    sourceRow: 284,
    date: "2024-11-27",
    action: "Buy",
    assetTicker: "ASX:FMG",
    quantity: 27,
    price: 18.64,
    fees: 4.99,
    currency: "AUD",
    platform: "Commsec Shares",
    assetClass: "Stock",
    sector: "Materials",
    country: "Australia",
    strategy: "Low Risk",
    notes: null
  },
  {
    id: "txn_000293",
    source: "initial_excel_import",
    sourceRow: 285,
    date: "2024-11-29",
    action: "Buy",
    assetTicker: "ETH-AUD",
    quantity: 0.08748003,
    price: 5659.00017353,
    fees: 4.95,
    currency: "AUD",
    platform: "Coinbase",
    assetClass: "Crypto",
    sector: "Crypto",
    country: "Crypto World",
    strategy: "High Risk",
    notes: null
  }
];
