import type { SeedTransaction } from "../types";

export const transactions018: SeedTransaction[] = [
  {
    id: "txn_000174",
    source: "initial_excel_import",
    sourceRow: 176,
    date: "2023-12-01",
    action: "Cash Interest",
    assetTicker: "Interest",
    quantity: 1,
    price: 0.18,
    fees: 0,
    currency: "AUD",
    platform: "CDIA - Dividends",
    assetClass: "Cash",
    sector: "Others",
    country: "Australia",
    strategy: "Dividend",
    notes: null
  },
  {
    id: "txn_000175",
    source: "initial_excel_import",
    sourceRow: 177,
    date: "2023-12-14",
    action: "Cash Deposit",
    assetTicker: "Cash",
    quantity: 1,
    price: 125.00,
    fees: 0,
    currency: "AUD",
    platform: "Commsec Bank",
    assetClass: "Cash",
    notes: "Kieren Chan"
  },
  {
    id: "txn_000176",
    source: "initial_excel_import",
    sourceRow: 178,
    date: "2023-12-18",
    action: "Cash Deposit",
    assetTicker: "Cash",
    quantity: 1,
    price: 125.00,
    fees: 0,
    currency: "AUD",
    platform: "Commsec Bank",
    assetClass: "Cash",
    notes: "Sam Thomas"
  },
  {
    id: "txn_000177",
    source: "initial_excel_import",
    sourceRow: 179,
    date: "2023-12-18",
    action: "Cash Deposit",
    assetTicker: "Cash",
    quantity: 1,
    price: 125.00,
    fees: 0,
    currency: "AUD",
    platform: "Commsec Bank",
    assetClass: "Cash",
    notes: "Tom Flitcroft"
  },
  {
    id: "txn_000178",
    source: "initial_excel_import",
    sourceRow: 180,
    date: "2023-12-22",
    action: "Cash Dividend",
    assetTicker: "ASX:GMG",
    quantity: 1,
    price: 7.12,
    fees: 0,
    currency: "AUD",
    platform: "CDIA - Dividends",
    assetClass: "Stock",
    sector: "Real Estate",
    country: "Australia",
    strategy: "Dividend",
    notes: null
  },
  {
    id: "txn_000179",
    source: "initial_excel_import",
    sourceRow: 181,
    date: "2024-01-02",
    action: "Cash Interest",
    assetTicker: "Interest",
    quantity: 1,
    price: 0.23,
    fees: 0,
    currency: "AUD",
    platform: "CDIA - Dividends",
    assetClass: "Cash",
    sector: "Others",
    country: "Australia",
    strategy: "Dividend",
    notes: null
  },
  {
    id: "txn_000180",
    source: "initial_excel_import",
    sourceRow: 182,
    date: "2024-01-15",
    action: "Cash Deposit",
    assetTicker: "Cash",
    quantity: 1,
    price: 125.00,
    fees: 0,
    currency: "AUD",
    platform: "Commsec Bank",
    assetClass: "Cash",
    notes: "Kieren Chan"
  },
  {
    id: "txn_000181",
    source: "initial_excel_import",
    sourceRow: 183,
    date: "2024-01-17",
    action: "Cash Dividend",
    assetTicker: "ASX:SEMI",
    quantity: 1,
    price: 2.46,
    fees: 0,
    currency: "AUD",
    platform: "CDIA - Dividends",
    assetClass: "Stock",
    sector: "Others",
    country: "Australia",
    strategy: "Dividend",
    notes: null
  },
  {
    id: "txn_000182",
    source: "initial_excel_import",
    sourceRow: 184,
    date: "2024-01-18",
    action: "Cash Deposit",
    assetTicker: "Cash",
    quantity: 1,
    price: 125.00,
    fees: 0,
    currency: "AUD",
    platform: "Commsec Bank",
    assetClass: "Cash",
    notes: "Sam Thomas"
  },
  {
    id: "txn_000183",
    source: "initial_excel_import",
    sourceRow: 185,
    date: "2024-01-19",
    action: "Cash Deposit",
    assetTicker: "Cash",
    quantity: 1,
    price: 125.00,
    fees: 0,
    currency: "AUD",
    platform: "Commsec Bank",
    assetClass: "Cash",
    notes: "Tom Flitcroft"
  }
];
