import type { SeedTransaction } from "../types";

export const transactions012: SeedTransaction[] = [
  {
    id: "txn_000114",
    source: "initial_excel_import",
    sourceRow: 116,
    date: "2023-02-14",
    action: "Cash Deposit",
    assetTicker: "Cash",
    quantity: 1,
    price: 125,
    fees: 0,
    currency: "AUD",
    platform: "Commsec Bank",
    assetClass: "Cash",
    notes: "Kieren Chan"
  },
  {
    id: "txn_000115",
    source: "initial_excel_import",
    sourceRow: 117,
    date: "2023-02-17",
    action: "Cash Deposit",
    assetTicker: "Cash",
    quantity: 1,
    price: 125,
    fees: 0,
    currency: "AUD",
    platform: "Commsec Bank",
    assetClass: "Cash",
    notes: "Sam Thomas"
  },
  {
    id: "txn_000116",
    source: "initial_excel_import",
    sourceRow: 118,
    date: "2023-02-24",
    action: "Cash Dividend",
    assetTicker: "ASX:GMG",
    quantity: 1,
    price: 3.35,
    fees: 0,
    currency: "AUD",
    platform: "CDIA - Dividends",
    assetClass: "Stock",
    sector: "Real Estate",
    country: "Australia",
    strategy: "Dividend",
    notes: null
  },
  {
    id: "txn_000117",
    source: "initial_excel_import",
    sourceRow: 119,
    date: "2023-03-01",
    action: "Cash Interest",
    assetTicker: "Interest",
    quantity: 1,
    price: 0.02,
    fees: 0,
    currency: "AUD",
    platform: "CDIA - Dividends",
    assetClass: "Cash",
    sector: "Others",
    country: "Australia",
    strategy: "Dividend",
    notes: null
  },
  {
    id: "txn_000118",
    source: "initial_excel_import",
    sourceRow: 120,
    date: "2023-03-14",
    action: "Cash Deposit",
    assetTicker: "Cash",
    quantity: 1,
    price: 125,
    fees: 0,
    currency: "AUD",
    platform: "Commsec Bank",
    assetClass: "Cash",
    notes: "Kieren Chan"
  },
  {
    id: "txn_000119",
    source: "initial_excel_import",
    sourceRow: 121,
    date: "2023-03-18",
    action: "Cash Deposit",
    assetTicker: "Cash",
    quantity: 1,
    price: 250,
    fees: 0,
    currency: "AUD",
    platform: "Commsec Bank",
    assetClass: "Cash",
    notes: "Tom Flitcroft"
  },
  {
    id: "txn_000120",
    source: "initial_excel_import",
    sourceRow: 122,
    date: "2023-03-19",
    action: "Cash Deposit",
    assetTicker: "Cash",
    quantity: 1,
    price: 125,
    fees: 0,
    currency: "AUD",
    platform: "Commsec Bank",
    assetClass: "Cash",
    notes: "Sam Thomas"
  },
  {
    id: "txn_000121",
    source: "initial_excel_import",
    sourceRow: 123,
    date: "2023-03-20",
    action: "Cash Dividend",
    assetTicker: "ASX:EDV",
    quantity: 1,
    price: 21.59,
    fees: 0,
    currency: "AUD",
    platform: "CDIA - Dividends",
    assetClass: "Stock",
    sector: "Consumer Staples",
    country: "Australia",
    strategy: "Dividend",
    notes: null
  },
  {
    id: "txn_000122",
    source: "initial_excel_import",
    sourceRow: 124,
    date: "2023-03-29",
    action: "Cash Dividend",
    assetTicker: "ASX:FMG",
    quantity: 1,
    price: 63.00,
    fees: 0,
    currency: "AUD",
    platform: "CDIA - Dividends",
    assetClass: "Stock",
    sector: "Materials",
    country: "Australia",
    strategy: "Dividend",
    notes: null
  },
  {
    id: "txn_000123",
    source: "initial_excel_import",
    sourceRow: 125,
    date: "2023-04-01",
    action: "Cash Interest",
    assetTicker: "Interest",
    quantity: 1,
    price: 0.16,
    fees: 0,
    currency: "AUD",
    platform: "CDIA - Dividends",
    assetClass: "Cash",
    sector: "Others",
    country: "Australia",
    strategy: "Dividend",
    notes: null
  }
];
