import type { SeedTransaction } from "../types";

export const transactions045: SeedTransaction[] = [
  {
    id: "txn_000444",
    source: "initial_excel_import",
    sourceRow: 436,
    date: "2026-04-01",
    action: "Cash Interest",
    assetTicker: "Interest",
    quantity: 1,
    price: 0.05,
    fees: 0,
    currency: "AUD",
    platform: "Commsec Bank",
    assetClass: "Cash",
    sector: "Others",
    country: "Australia",
    strategy: "Dividend",
    notes: null
  },
  {
    id: "txn_000445",
    source: "initial_excel_import",
    sourceRow: 437,
    date: "2026-04-14",
    action: "Cash Deposit",
    assetTicker: "Cash",
    quantity: 1,
    price: 175.00,
    fees: 0,
    currency: "AUD",
    platform: "Commsec Bank",
    assetClass: "Cash",
    notes: "Kieren Chan"
  },
  {
    id: "txn_000446",
    source: "initial_excel_import",
    sourceRow: 438,
    date: "2026-04-15",
    action: "Cash Deposit",
    assetTicker: "Cash",
    quantity: 1,
    price: 175.00,
    fees: 0,
    currency: "AUD",
    platform: "Commsec Bank",
    assetClass: "Cash",
    notes: "Sam Thomas"
  },
  {
    id: "txn_000447",
    source: "initial_excel_import",
    sourceRow: 439,
    date: "2026-04-16",
    action: "Cash Deposit",
    assetTicker: "Cash",
    quantity: 1,
    price: 175.00,
    fees: 0,
    currency: "AUD",
    platform: "Commsec Bank",
    assetClass: "Cash",
    notes: "Tom Flitcroft"
  },
  {
    id: "txn_000448",
    source: "initial_excel_import",
    sourceRow: 440,
    date: "2026-04-16",
    action: "Cash Dividend",
    assetTicker: "VAS.AX",
    quantity: 1,
    price: 7.88,
    fees: 0,
    currency: "AUD",
    platform: "CDIA - Dividends",
    assetClass: "ETF",
    sector: "ETF",
    country: "Australia",
    strategy: "Dividend",
    notes: null
  },
  {
    id: "txn_000449",
    source: "initial_excel_import",
    sourceRow: 441,
    date: "2026-04-17",
    action: "Cash Dividend",
    assetTicker: "ASX:SEMI",
    quantity: 1,
    price: 72.64,
    fees: 0,
    currency: "AUD",
    platform: "CDIA - Dividends",
    assetClass: "ETF",
    sector: "Technology",
    country: "Australia",
    strategy: "Dividend",
    notes: null
  },
  {
    id: "txn_000450",
    source: "initial_excel_import",
    sourceRow: 442,
    date: "2026-04-24",
    action: "Cash Dividend",
    assetTicker: "NYSE:ALB",
    quantity: 1,
    price: 5.91,
    fees: 0,
    currency: "USD",
    platform: "Commsec International Shares",
    assetClass: "Stock",
    sector: "Materials",
    country: "United States",
    strategy: "Dividend",
    notes: null
  },
  {
    id: "txn_000451",
    source: "initial_excel_import",
    sourceRow: 443,
    date: "2026-04-30",
    action: "Cash Interest",
    assetTicker: "Interest",
    quantity: 1,
    price: 0.05,
    fees: 0,
    currency: "AUD",
    platform: "Commsec Bank",
    assetClass: "Cash",
    sector: "Others",
    country: "Australia",
    strategy: "Dividend",
    notes: null
  },
  {
    id: "txn_000452",
    source: "initial_excel_import",
    sourceRow: 444,
    date: "2026-04-30",
    action: "Portfolio Snapshot",
    assetTicker: "Portfolio",
    quantity: 1,
    price: 0,
    fees: 0,
    currency: "AUD",
    platform: "TradeHub",
    assetClass: "System",
    notes: "Imported history checkpoint"
  },
  {
    id: "txn_000453",
    source: "initial_excel_import",
    sourceRow: 445,
    date: "2026-04-30",
    action: "Import Complete",
    assetTicker: "SYSTEM",
    quantity: 1,
    price: 0,
    fees: 0,
    currency: "AUD",
    platform: "TradeHub",
    assetClass: "System",
    notes: "End of historical Excel import"
  }
];
