import type { SeedTransaction } from "../types";

export const transactions030: SeedTransaction[] = [
  {
    id: "txn_000294",
    source: "initial_excel_import",
    sourceRow: 286,
    date: "2024-11-29",
    action: "Buy",
    assetTicker: "SOL-AUD",
    quantity: 1.56262197,
    price: 380.48515051,
    fees: 5.95,
    currency: "AUD",
    platform: "Coinbase",
    assetClass: "Crypto",
    sector: "Crypto",
    country: "Crypto World",
    strategy: "High Risk",
    notes: null
  },
  {
    id: "txn_000295",
    source: "initial_excel_import",
    sourceRow: 287,
    date: "2024-11-29",
    action: "Sell",
    assetTicker: "VET-AUD",
    quantity: 1212.24446407,
    price: 0.20418713,
    fees: 0.77,
    currency: "AUD",
    platform: "Coinbase",
    assetClass: "Crypto",
    sector: "Crypto",
    country: "Crypto World",
    strategy: "High Risk",
    notes: null
  },
  {
    id: "txn_000296",
    source: "initial_excel_import",
    sourceRow: 288,
    date: "2024-11-29",
    action: "Sell",
    assetTicker: "EOS-AUD",
    quantity: 20.1,
    price: 12.44,
    fees: 0.25,
    currency: "AUD",
    platform: "Coinbase",
    assetClass: "Crypto",
    sector: "Crypto",
    country: "Crypto World",
    strategy: "High Risk",
    notes: null
  },
  {
    id: "txn_000297",
    source: "initial_excel_import",
    sourceRow: 289,
    date: "2024-12-01",
    action: "Cash Interest",
    assetTicker: "Interest",
    quantity: 1,
    price: 0.11,
    fees: 0,
    currency: "AUD",
    platform: "CDIA - Dividends",
    assetClass: "Cash",
    sector: "Others",
    country: "Australia",
    strategy: "Dividend",
    notes: null
  },
  {
    id: "txn_000298",
    source: "initial_excel_import",
    sourceRow: 290,
    date: "2024-12-03",
    action: "Cash Deposit",
    assetTicker: "Cash",
    quantity: 1,
    price: 125,
    fees: 0,
    currency: "AUD",
    platform: "Commsec Bank",
    assetClass: "Cash",
    notes: "Kieren Chan"
  },
  {
    id: "txn_000299",
    source: "initial_excel_import",
    sourceRow: 291,
    date: "2024-12-03",
    action: "Cash Withdrawal",
    assetTicker: "Cash",
    quantity: 1,
    price: 1000,
    fees: 0,
    currency: "AUD",
    platform: "Commsec Bank",
    assetClass: "Cash",
    notes: "Coin Spot"
  },
  {
    id: "txn_000300",
    source: "initial_excel_import",
    sourceRow: 292,
    date: "2024-12-09",
    action: "Cash Deposit",
    assetTicker: "Cash",
    quantity: 1,
    price: 125,
    fees: 0,
    currency: "AUD",
    platform: "Commsec Bank",
    assetClass: "Cash",
    notes: "Marc Mario"
  },
  {
    id: "txn_000301",
    source: "initial_excel_import",
    sourceRow: 293,
    date: "2024-12-16",
    action: "Cash Dividend",
    assetTicker: "ASX:NAB",
    quantity: 1,
    price: 31.45,
    fees: 0,
    currency: "AUD",
    platform: "CDIA - Dividends",
    assetClass: "Stock",
    sector: "Financials",
    country: "Australia",
    strategy: "Dividend",
    notes: null
  },
  {
    id: "txn_000302",
    source: "initial_excel_import",
    sourceRow: 294,
    date: "2024-12-17",
    action: "Cash Deposit",
    assetTicker: "Cash",
    quantity: 1,
    price: 125,
    fees: 0,
    currency: "AUD",
    platform: "Commsec Bank",
    assetClass: "Cash",
    notes: "Sam Thomas"
  },
  {
    id: "txn_000303",
    source: "initial_excel_import",
    sourceRow: 295,
    date: "2024-12-18",
    action: "Cash Deposit",
    assetTicker: "Cash",
    quantity: 1,
    price: 125,
    fees: 0,
    currency: "AUD",
    platform: "Commsec Bank",
    assetClass: "Cash",
    notes: "Tom Flitcroft"
  }
];
