import type { SeedTransaction } from "../types";

export const transactions042: SeedTransaction[] = [
  {
    id: "txn_000414",
    source: "initial_excel_import",
    sourceRow: 406,
    date: "2025-11-26",
    action: "Cash Dividend",
    assetTicker: "ASX:GMG",
    quantity: 1,
    price: 6.43,
    fees: 0,
    currency: "AUD",
    platform: "CDIA - Dividends",
    assetClass: "Stock",
    sector: "Real Estate",
    country: "Australia",
    strategy: "Dividend",
    notes: null
  },
  {
    id: "txn_000415",
    source: "initial_excel_import",
    sourceRow: 407,
    date: "2025-11-28",
    action: "Cash Dividend",
    assetTicker: "ASX:NAB",
    quantity: 1,
    price: 36.92,
    fees: 0,
    currency: "AUD",
    platform: "CDIA - Dividends",
    assetClass: "Stock",
    sector: "Financials",
    country: "Australia",
    strategy: "Dividend",
    notes: null
  },
  {
    id: "txn_000416",
    source: "initial_excel_import",
    sourceRow: 408,
    date: "2025-12-01",
    action: "Cash Interest",
    assetTicker: "Interest",
    quantity: 1,
    price: 0.03,
    fees: 0,
    currency: "AUD",
    platform: "CDIA - Dividends",
    assetClass: "Cash",
    sector: "Others",
    country: "Australia",
    strategy: "Dividend",
    notes: null
  },
  {
    id: "txn_000417",
    source: "initial_excel_import",
    sourceRow: 409,
    date: "2025-12-12",
    action: "Cash Deposit",
    assetTicker: "Cash",
    quantity: 1,
    price: 175.00,
    fees: 0,
    currency: "AUD",
    platform: "Commsec Bank",
    assetClass: "Cash",
    notes: "Kieren Chan"
  },
  {
    id: "txn_000418",
    source: "initial_excel_import",
    sourceRow: 410,
    date: "2025-12-15",
    action: "Cash Deposit",
    assetTicker: "Cash",
    quantity: 1,
    price: 175.00,
    fees: 0,
    currency: "AUD",
    platform: "Commsec Bank",
    assetClass: "Cash",
    notes: "Sam Thomas"
  },
  {
    id: "txn_000419",
    source: "initial_excel_import",
    sourceRow: 411,
    date: "2025-12-16",
    action: "Cash Deposit",
    assetTicker: "Cash",
    quantity: 1,
    price: 175.00,
    fees: 0,
    currency: "AUD",
    platform: "Commsec Bank",
    assetClass: "Cash",
    notes: "Tom Flitcroft"
  },
  {
    id: "txn_000420",
    source: "initial_excel_import",
    sourceRow: 412,
    date: "2025-12-24",
    action: "Cash Dividend",
    assetTicker: "NYSE:ALB",
    quantity: 1,
    price: 5.62,
    fees: 0,
    currency: "USD",
    platform: "Commsec International Shares",
    assetClass: "Stock",
    sector: "Materials",
    country: "United States",
    strategy: "Dividend",
    notes: null
  },
  {
    id: "txn_000421",
    source: "initial_excel_import",
    sourceRow: 413,
    date: "2025-12-29",
    action: "Cash Dividend",
    assetTicker: "ASX:FMG",
    quantity: 1,
    price: 82.16,
    fees: 0,
    currency: "AUD",
    platform: "CDIA - Dividends",
    assetClass: "Stock",
    sector: "Materials",
    country: "Australia",
    strategy: "Dividend",
    notes: null
  },
  {
    id: "txn_000422",
    source: "initial_excel_import",
    sourceRow: 414,
    date: "2025-12-31",
    action: "Cash Interest",
    assetTicker: "Interest",
    quantity: 1,
    price: 0.04,
    fees: 0,
    currency: "AUD",
    platform: "CDIA - Dividends",
    assetClass: "Cash",
    sector: "Others",
    country: "Australia",
    strategy: "Dividend",
    notes: null
  },
  {
    id: "txn_000423",
    source: "initial_excel_import",
    sourceRow: 415,
    date: "2025-12-31",
    action: "Year End Adjustment",
    assetTicker: "Cash",
    quantity: 1,
    price: 0.00,
    fees: 0,
    currency: "AUD",
    platform: "Commsec Bank",
    assetClass: "Cash",
    notes: "End of imported transaction history"
  }
];
