import type { SeedTransaction } from "../types";

export const transactions010: SeedTransaction[] = [
  {
    id: "txn_000094",
    source: "initial_excel_import",
    sourceRow: 96,
    date: "2022-10-02",
    action: "Cash Deposit",
    assetTicker: "Cash",
    quantity: 1,
    price: 125,
    fees: 0,
    currency: "AUD",
    platform: "Commsec Bank",
    assetClass: "Cash",
    notes: "Marc Mario"
  },
  {
    id: "txn_000095",
    source: "initial_excel_import",
    sourceRow: 97,
    date: "2022-10-18",
    action: "Cash Deposit",
    assetTicker: "Cash",
    quantity: 1,
    price: 125,
    fees: 0,
    currency: "AUD",
    platform: "Commsec Bank",
    assetClass: "Cash",
    notes: "Sam Thomas"
  },
  {
    id: "txn_000096",
    source: "initial_excel_import",
    sourceRow: 98,
    date: "2022-10-26",
    action: "Cash Deposit",
    assetTicker: "Cash",
    quantity: 1,
    price: 250,
    fees: 0,
    currency: "AUD",
    platform: "Commsec Bank",
    assetClass: "Cash",
    notes: "Tom Flitcroft"
  },
  {
    id: "txn_000097",
    source: "initial_excel_import",
    sourceRow: 99,
    date: "2022-11-12",
    action: "Cash Withdrawal",
    assetTicker: "Cash",
    quantity: 1,
    price: 1000,
    fees: 0,
    currency: "AUD",
    platform: "Commsec Bank",
    assetClass: "Cash",
    notes: "Coin Spot"
  },
  {
    id: "txn_000098",
    source: "initial_excel_import",
    sourceRow: 100,
    date: "2022-11-14",
    action: "Cash Deposit",
    assetTicker: "Cash",
    quantity: 1,
    price: 125,
    fees: 0,
    currency: "AUD",
    platform: "Commsec Bank",
    assetClass: "Cash",
    notes: "Kieren Chan"
  },
  {
    id: "txn_000099",
    source: "initial_excel_import",
    sourceRow: 101,
    date: "2022-11-14",
    action: "Cash Deposit",
    assetTicker: "Cash",
    quantity: 1,
    price: 125,
    fees: 0,
    currency: "AUD",
    platform: "Commsec Bank",
    assetClass: "Cash",
    notes: "Kieren Chan"
  },
  {
    id: "txn_000100",
    source: "initial_excel_import",
    sourceRow: 102,
    date: "2022-11-16",
    action: "Transfer Send",
    assetTicker: "Cash",
    quantity: 1,
    price: 2000,
    fees: 0,
    currency: "AUD",
    platform: "Commsec Shares",
    assetClass: "Cash",
    notes: null
  },
  {
    id: "txn_000101",
    source: "initial_excel_import",
    sourceRow: 103,
    date: "2022-11-16",
    action: "Buy",
    assetTicker: "ASX:GMG",
    quantity: 29,
    price: 18.04,
    fees: 10,
    currency: "AUD",
    platform: "Commsec Shares",
    assetClass: "Stock",
    sector: "Real Estate",
    country: "Australia",
    strategy: "Low Risk",
    notes: null
  },
  {
    id: "txn_000102",
    source: "initial_excel_import",
    sourceRow: 104,
    date: "2022-11-16",
    action: "Buy",
    assetTicker: "ASX:FMG",
    quantity: 26,
    price: 19.79,
    fees: 10,
    currency: "AUD",
    platform: "Commsec Shares",
    assetClass: "Stock",
    sector: "Materials",
    country: "Australia",
    strategy: "Low Risk",
    notes: "Dividend"
  },
  {
    id: "txn_000103",
    source: "initial_excel_import",
    sourceRow: 105,
    date: "2022-11-16",
    action: "Buy",
    assetTicker: "ASX:AIZ",
    quantity: 700,
    price: 0.73,
    fees: 10,
    currency: "AUD",
    platform: "Commsec Shares",
    assetClass: "Stock",
    sector: "Others",
    country: "Australia",
    strategy: "Low Risk",
    notes: null
  }
];
