import type { SeedTransaction } from "../types";

export const transactions023: SeedTransaction[] = [
  {
    id: "txn_000224",
    source: "initial_excel_import",
    sourceRow: 226,
    date: "2024-09-01",
    action: "Cash Interest",
    assetTicker: "Interest",
    quantity: 1,
    price: 0.74,
    fees: 0,
    currency: "AUD",
    platform: "CDIA - Dividends",
    assetClass: "Cash",
    sector: "Others",
    country: "Australia",
    strategy: "Dividend",
    notes: null
  },
  {
    id: "txn_000225",
    source: "initial_excel_import",
    sourceRow: 227,
    date: "2024-09-13",
    action: "Cash Deposit",
    assetTicker: "Cash",
    quantity: 1,
    price: 125.00,
    fees: 0,
    currency: "AUD",
    platform: "Commsec Bank",
    assetClass: "Cash",
    notes: "Kieren Chan"
  },
  {
    id: "txn_000226",
    source: "initial_excel_import",
    sourceRow: 228,
    date: "2024-09-17",
    action: "Cash Deposit",
    assetTicker: "Cash",
    quantity: 1,
    price: 125.00,
    fees: 0,
    currency: "AUD",
    platform: "Commsec Bank",
    assetClass: "Cash",
    notes: "Sam Thomas"
  },
  {
    id: "txn_000227",
    source: "initial_excel_import",
    sourceRow: 229,
    date: "2024-09-18",
    action: "Cash Deposit",
    assetTicker: "Cash",
    quantity: 1,
    price: 125.00,
    fees: 0,
    currency: "AUD",
    platform: "Commsec Bank",
    assetClass: "Cash",
    notes: "Tom Flitcroft"
  },
  {
    id: "txn_000228",
    source: "initial_excel_import",
    sourceRow: 230,
    date: "2024-09-20",
    action: "Cash Dividend",
    assetTicker: "ASX:EDV",
    quantity: 1,
    price: 23.41,
    fees: 0,
    currency: "AUD",
    platform: "CDIA - Dividends",
    assetClass: "Stock",
    sector: "Consumer Staples",
    country: "Australia",
    strategy: "Dividend",
    notes: null
  },
  {
    id: "txn_000229",
    source: "initial_excel_import",
    sourceRow: 231,
    date: "2024-09-26",
    action: "Cash Dividend",
    assetTicker: "ASX:FMG",
    quantity: 1,
    price: 128.93,
    fees: 0,
    currency: "AUD",
    platform: "CDIA - Dividends",
    assetClass: "Stock",
    sector: "Materials",
    country: "Australia",
    strategy: "Dividend",
    notes: null
  },
  {
    id: "txn_000230",
    source: "initial_excel_import",
    sourceRow: 232,
    date: "2024-10-01",
    action: "Cash Interest",
    assetTicker: "Interest",
    quantity: 1,
    price: 0.81,
    fees: 0,
    currency: "AUD",
    platform: "CDIA - Dividends",
    assetClass: "Cash",
    sector: "Others",
    country: "Australia",
    strategy: "Dividend",
    notes: null
  },
  {
    id: "txn_000231",
    source: "initial_excel_import",
    sourceRow: 233,
    date: "2024-10-14",
    action: "Cash Deposit",
    assetTicker: "Cash",
    quantity: 1,
    price: 125.00,
    fees: 0,
    currency: "AUD",
    platform: "Commsec Bank",
    assetClass: "Cash",
    notes: "Kieren Chan"
  },
  {
    id: "txn_000232",
    source: "initial_excel_import",
    sourceRow: 234,
    date: "2024-10-18",
    action: "Cash Deposit",
    assetTicker: "Cash",
    quantity: 1,
    price: 125.00,
    fees: 0,
    currency: "AUD",
    platform: "Commsec Bank",
    assetClass: "Cash",
    notes: "Sam Thomas"
  },
  {
    id: "txn_000233",
    source: "initial_excel_import",
    sourceRow: 235,
    date: "2024-10-21",
    action: "Cash Deposit",
    assetTicker: "Cash",
    quantity: 1,
    price: 125.00,
    fees: 0,
    currency: "AUD",
    platform: "Commsec Bank",
    assetClass: "Cash",
    notes: "Tom Flitcroft"
  }
];
