import type { SeedTransaction } from "../types";

export const transactions014: SeedTransaction[] = [
  {
    id: "txn_000134",
    source: "initial_excel_import",
    sourceRow: 136,
    date: "2023-06-01",
    action: "Cash Interest",
    assetTicker: "Interest",
    quantity: 1,
    price: 0.21,
    fees: 0,
    currency: "AUD",
    platform: "CDIA - Dividends",
    assetClass: "Cash",
    sector: "Others",
    country: "Australia",
    strategy: "Dividend",
    notes: null
  },
  {
    id: "txn_000135",
    source: "initial_excel_import",
    sourceRow: 137,
    date: "2023-06-02",
    action: "Cash Withdrawal",
    assetTicker: "Cash",
    quantity: 1,
    price: 500,
    fees: 0,
    currency: "AUD",
    platform: "Commsec Bank",
    assetClass: "Cash",
    notes: "Tom Owed Money to"
  },
  {
    id: "txn_000136",
    source: "initial_excel_import",
    sourceRow: 138,
    date: "2023-06-03",
    action: "Cash Deposit",
    assetTicker: "Cash",
    quantity: 1,
    price: 625,
    fees: 0,
    currency: "AUD",
    platform: "Commsec Bank",
    assetClass: "Cash",
    notes: "Marc Mario"
  },
  {
    id: "txn_000137",
    source: "initial_excel_import",
    sourceRow: 139,
    date: "2023-06-14",
    action: "Cash Deposit",
    assetTicker: "Cash",
    quantity: 1,
    price: 125,
    fees: 0,
    currency: "AUD",
    platform: "Commsec Bank",
    assetClass: "Cash",
    notes: "Kieren Chan"
  },
  {
    id: "txn_000138",
    source: "initial_excel_import",
    sourceRow: 140,
    date: "2023-06-19",
    action: "Cash Deposit",
    assetTicker: "Cash",
    quantity: 1,
    price: 125,
    fees: 0,
    currency: "AUD",
    platform: "Commsec Bank",
    assetClass: "Cash",
    notes: "Tom Flitcroft"
  },
  {
    id: "txn_000139",
    source: "initial_excel_import",
    sourceRow: 141,
    date: "2023-06-20",
    action: "Cash Deposit",
    assetTicker: "Cash",
    quantity: 1,
    price: 125,
    fees: 0,
    currency: "AUD",
    platform: "Commsec Bank",
    assetClass: "Cash",
    notes: "Sam Thomas"
  },
  {
    id: "txn_000140",
    source: "initial_excel_import",
    sourceRow: 142,
    date: "2023-06-28",
    action: "Transfer Send",
    assetTicker: "Cash",
    quantity: 1,
    price: 3000,
    fees: 0,
    currency: "AUD",
    platform: "Commsec Shares",
    assetClass: "Cash",
    notes: "June Shares"
  },
  {
    id: "txn_000141",
    source: "initial_excel_import",
    sourceRow: 143,
    date: "2023-06-28",
    action: "Buy",
    assetTicker: "ASX:GMG",
    quantity: 25,
    price: 20.11,
    fees: 10,
    currency: "AUD",
    platform: "Commsec Shares",
    assetClass: "Stock",
    sector: "Real Estate",
    country: "Australia",
    strategy: "Low Risk",
    notes: null
  },
  {
    id: "txn_000142",
    source: "initial_excel_import",
    sourceRow: 144,
    date: "2023-06-28",
    action: "Buy",
    assetTicker: "ASX:AIZ",
    quantity: 700,
    price: 0.72,
    fees: 10,
    currency: "AUD",
    platform: "Commsec Shares",
    assetClass: "Stock",
    sector: "Others",
    country: "Australia",
    strategy: "Low Risk",
    notes: null
  },
  {
    id: "txn_000143",
    source: "initial_excel_import",
    sourceRow: 145,
    date: "2023-06-28",
    action: "Buy",
    assetTicker: "ASX:FMG",
    quantity: 22,
    price: 22.01,
    fees: 10,
    currency: "AUD",
    platform: "Commsec Shares",
    assetClass: "Stock",
    sector: "Materials",
    country: "Australia",
    strategy: "Low Risk",
    notes: "Dividend"
  }
];
