import type { SeedTransaction } from "../types";

export const transactions035: SeedTransaction[] = [
  {
    id: "txn_000344",
    source: "initial_excel_import",
    sourceRow: 336,
    date: "2025-05-26",
    action: "Transfer Deposit",
    assetTicker: "Cash",
    quantity: 1,
    price: 776.78,
    fees: 0,
    currency: "AUD",
    platform: "Commsec Bank",
    assetClass: "Cash",
    notes: null
  },
  {
    id: "txn_000345",
    source: "initial_excel_import",
    sourceRow: 337,
    date: "2025-06-01",
    action: "Cash Interest",
    assetTicker: "Interest",
    quantity: 1,
    price: 0.02,
    fees: 0,
    currency: "AUD",
    platform: "CDIA - Dividends",
    assetClass: "Cash",
    sector: "Others",
    country: "Australia",
    strategy: "Dividend",
    notes: null
  },
  {
    id: "txn_000346",
    source: "initial_excel_import",
    sourceRow: 338,
    date: "2025-06-01",
    action: "Cash Interest",
    assetTicker: "Interest",
    quantity: 1,
    price: 0.02,
    fees: 0,
    currency: "AUD",
    platform: "Commsec Bank",
    assetClass: "Cash",
    notes: null
  },
  {
    id: "txn_000347",
    source: "initial_excel_import",
    sourceRow: 339,
    date: "2025-06-18",
    action: "Cash Deposit",
    assetTicker: "Cash",
    quantity: 1,
    price: 150.00,
    fees: 0,
    currency: "AUD",
    platform: "Commsec Bank",
    assetClass: "Cash",
    notes: null
  },
  {
    id: "txn_000348",
    source: "initial_excel_import",
    sourceRow: 340,
    date: "2025-06-19",
    action: "Cash Deposit",
    assetTicker: "Cash",
    quantity: 1,
    price: 150.00,
    fees: 0,
    currency: "AUD",
    platform: "Commsec Bank",
    assetClass: "Cash",
    notes: null
  },
  {
    id: "txn_000349",
    source: "initial_excel_import",
    sourceRow: 341,
    date: "2025-07-02",
    action: "Cash Dividend",
    assetTicker: "ASX:NAB",
    quantity: 1,
    price: 31.45,
    fees: 0,
    currency: "AUD",
    platform: "Commsec Bank",
    assetClass: "Stock",
    sector: "Financials",
    country: "Australia",
    strategy: "Dividend",
    notes: null
  },
  {
    id: "txn_000350",
    source: "initial_excel_import",
    sourceRow: 342,
    date: "2025-07-16",
    action: "Sell",
    assetTicker: "ETH-AUD",
    quantity: 0.248,
    price: 4822.91,
    fees: 11.9608168,
    currency: "AUD",
    platform: "Coinbase",
    assetClass: "Crypto",
    sector: "Crypto",
    country: "Crypto World",
    strategy: "High Risk",
    notes: null
  },
  {
    id: "txn_000351",
    source: "initial_excel_import",
    sourceRow: 343,
    date: "2025-07-16",
    action: "Transfer Deposit",
    assetTicker: "Cash",
    quantity: 1,
    price: 1184.12,
    fees: 0,
    currency: "AUD",
    platform: "Commsec Bank",
    assetClass: "Cash",
    notes: null
  },
  {
    id: "txn_000352",
    source: "initial_excel_import",
    sourceRow: 344,
    date: "2025-07-16",
    action: "Cash Dividend",
    assetTicker: "VAS.AX",
    quantity: 1,
    price: 4.15,
    fees: 0,
    currency: "AUD",
    platform: "Commsec Bank",
    assetClass: "ETF",
    sector: "ETF",
    country: "Australia",
    strategy: "Dividend",
    notes: null
  },
  {
    id: "txn_000353",
    source: "initial_excel_import",
    sourceRow: 345,
    date: "2025-07-16",
    action: "Cash Dividend",
    assetTicker: "ASX:SEMI",
    quantity: 1,
    price: 62.77,
    fees: 0,
    currency: "AUD",
    platform: "Commsec Bank",
    assetClass: "Stock",
    sector: "Others",
    country: "Australia",
    strategy: "Dividend",
    notes: null
  }
];
