import type { SeedTransaction } from "../types";

export const transactions034: SeedTransaction[] = [
  {
    id: "txn_000334",
    source: "initial_excel_import",
    sourceRow: 326,
    date: "2025-05-01",
    action: "Cash Interest",
    assetTicker: "Interest",
    quantity: 1,
    price: 0.03,
    fees: 0,
    currency: "AUD",
    platform: "CDIA - Dividends",
    assetClass: "Cash",
    sector: "Others",
    country: "Australia",
    strategy: "Dividend",
    notes: null
  },
  {
    id: "txn_000335",
    source: "initial_excel_import",
    sourceRow: 327,
    date: "2025-05-06",
    action: "Cash Deposit",
    assetTicker: "Cash",
    quantity: 1,
    price: 150.00,
    fees: 0,
    currency: "AUD",
    platform: "Commsec Bank",
    assetClass: "Cash",
    notes: "Kieren Chan"
  },
  {
    id: "txn_000336",
    source: "initial_excel_import",
    sourceRow: 328,
    date: "2025-05-15",
    action: "Cash Deposit",
    assetTicker: "Cash",
    quantity: 1,
    price: 150.00,
    fees: 0,
    currency: "AUD",
    platform: "Commsec Bank",
    assetClass: "Cash",
    notes: "Sam Thomas"
  },
  {
    id: "txn_000337",
    source: "initial_excel_import",
    sourceRow: 329,
    date: "2025-05-19",
    action: "Sell",
    assetTicker: "ASX:LGP",
    quantity: 6900,
    price: 0.11,
    fees: 4.99,
    currency: "AUD",
    platform: "Commsec Shares",
    assetClass: "Stock",
    sector: "Healthcare",
    country: "Australia",
    strategy: "Low Risk",
    notes: null
  },
  {
    id: "txn_000338",
    source: "initial_excel_import",
    sourceRow: 330,
    date: "2025-05-19",
    action: "Sell",
    assetTicker: "ASX:AIZ",
    quantity: 1400,
    price: 0.55,
    fees: 4.99,
    currency: "AUD",
    platform: "Commsec Shares",
    assetClass: "Stock",
    sector: "Others",
    country: "Australia",
    strategy: "Low Risk",
    notes: null
  },
  {
    id: "txn_000339",
    source: "initial_excel_import",
    sourceRow: 331,
    date: "2025-05-19",
    action: "Cash Deposit",
    assetTicker: "Cash",
    quantity: 1,
    price: 150.00,
    fees: 0,
    currency: "AUD",
    platform: "Commsec Bank",
    assetClass: "Cash",
    notes: "Tom Flitcroft"
  },
  {
    id: "txn_000340",
    source: "initial_excel_import",
    sourceRow: 332,
    date: "2025-05-20",
    action: "Sell",
    assetTicker: "NYSE:LMT",
    quantity: 1,
    price: 716.27,
    fees: 0,
    currency: "AUD",
    platform: "Commsec International Shares",
    assetClass: "Stock",
    sector: "Others",
    country: "Australia",
    strategy: "Low Risk",
    notes: null
  },
  {
    id: "txn_000341",
    source: "initial_excel_import",
    sourceRow: 333,
    date: "2025-05-21",
    action: "Transfer Deposit",
    assetTicker: "Cash",
    quantity: 1,
    price: 1519.73,
    fees: 0,
    currency: "AUD",
    platform: "Commsec Bank",
    assetClass: "Cash",
    notes: null
  },
  {
    id: "txn_000342",
    source: "initial_excel_import",
    sourceRow: 334,
    date: "2025-05-26",
    action: "Cash Deposit",
    assetTicker: "Cash",
    quantity: 1,
    price: 150.00,
    fees: 0,
    currency: "AUD",
    platform: "Commsec Bank",
    assetClass: "Cash",
    notes: "Kieren Chan"
  },
  {
    id: "txn_000343",
    source: "initial_excel_import",
    sourceRow: 335,
    date: "2025-05-26",
    action: "Cash Withdrawal",
    assetTicker: "Cash",
    quantity: 1,
    price: 6042.43,
    fees: 0,
    currency: "AUD",
    platform: "Commsec Bank",
    assetClass: "Cash",
    notes: "Marc Mario"
  }
];
