import type { SeedTransaction } from "../types";

export const transactions024: SeedTransaction[] = [
  {
    id: "txn_000234",
    source: "initial_excel_import",
    sourceRow: 236,
    date: "2024-11-01",
    action: "Cash Interest",
    assetTicker: "Interest",
    quantity: 1,
    price: 0.93,
    fees: 0,
    currency: "AUD",
    platform: "CDIA - Dividends",
    assetClass: "Cash",
    sector: "Others",
    country: "Australia",
    strategy: "Dividend",
    notes: null
  },
  {
    id: "txn_000235",
    source: "initial_excel_import",
    sourceRow: 237,
    date: "2024-11-14",
    action: "Cash Deposit",
    assetTicker: "Cash",
    quantity: 1,
    price: 125.00,
    fees: 0,
    currency: "AUD",
    platform: "Commsec Bank",
    assetClass: "Cash",
    notes: "Kieren Chan"
  },
  {
    id: "txn_000236",
    source: "initial_excel_import",
    sourceRow: 238,
    date: "2024-11-18",
    action: "Cash Deposit",
    assetTicker: "Cash",
    quantity: 1,
    price: 125.00,
    fees: 0,
    currency: "AUD",
    platform: "Commsec Bank",
    assetClass: "Cash",
    notes: "Sam Thomas"
  },
  {
    id: "txn_000237",
    source: "initial_excel_import",
    sourceRow: 239,
    date: "2024-11-19",
    action: "Cash Deposit",
    assetTicker: "Cash",
    quantity: 1,
    price: 125.00,
    fees: 0,
    currency: "AUD",
    platform: "Commsec Bank",
    assetClass: "Cash",
    notes: "Tom Flitcroft"
  },
  {
    id: "txn_000238",
    source: "initial_excel_import",
    sourceRow: 240,
    date: "2024-11-26",
    action: "Cash Dividend",
    assetTicker: "ASX:GMG",
    quantity: 1,
    price: 8.36,
    fees: 0,
    currency: "AUD",
    platform: "CDIA - Dividends",
    assetClass: "Stock",
    sector: "Real Estate",
    country: "Australia",
    strategy: "Dividend",
    notes: null
  },
  {
    id: "txn_000239",
    source: "initial_excel_import",
    sourceRow: 241,
    date: "2024-11-29",
    action: "Cash Dividend",
    assetTicker: "ASX:NAB",
    quantity: 1,
    price: 44.72,
    fees: 0,
    currency: "AUD",
    platform: "CDIA - Dividends",
    assetClass: "Stock",
    sector: "Financials",
    country: "Australia",
    strategy: "Dividend",
    notes: null
  },
  {
    id: "txn_000240",
    source: "initial_excel_import",
    sourceRow: 242,
    date: "2024-12-01",
    action: "Cash Interest",
    assetTicker: "Interest",
    quantity: 1,
    price: 1.02,
    fees: 0,
    currency: "AUD",
    platform: "CDIA - Dividends",
    assetClass: "Cash",
    sector: "Others",
    country: "Australia",
    strategy: "Dividend",
    notes: null
  },
  {
    id: "txn_000241",
    source: "initial_excel_import",
    sourceRow: 243,
    date: "2024-12-13",
    action: "Cash Deposit",
    assetTicker: "Cash",
    quantity: 1,
    price: 125.00,
    fees: 0,
    currency: "AUD",
    platform: "Commsec Bank",
    assetClass: "Cash",
    notes: "Kieren Chan"
  },
  {
    id: "txn_000242",
    source: "initial_excel_import",
    sourceRow: 244,
    date: "2024-12-18",
    action: "Cash Deposit",
    assetTicker: "Cash",
    quantity: 1,
    price: 125.00,
    fees: 0,
    currency: "AUD",
    platform: "Commsec Bank",
    assetClass: "Cash",
    notes: "Sam Thomas"
  },
  {
    id: "txn_000243",
    source: "initial_excel_import",
    sourceRow: 245,
    date: "2024-12-19",
    action: "Cash Deposit",
    assetTicker: "Cash",
    quantity: 1,
    price: 125.00,
    fees: 0,
    currency: "AUD",
    platform: "Commsec Bank",
    assetClass: "Cash",
    notes: "Tom Flitcroft"
  }
];
