import type { SeedTransaction } from "../types";

export const transactions013: SeedTransaction[] = [
  {
    id: "txn_000124",
    source: "initial_excel_import",
    sourceRow: 126,
    date: "2023-04-13",
    action: "Cash Deposit",
    assetTicker: "Cash",
    quantity: 1,
    price: 125,
    fees: 0,
    currency: "AUD",
    platform: "Commsec Bank",
    assetClass: "Cash",
    notes: "Kieren Chan"
  },
  {
    id: "txn_000125",
    source: "initial_excel_import",
    sourceRow: 127,
    date: "2023-04-18",
    action: "Cash Deposit",
    assetTicker: "Cash",
    quantity: 1,
    price: 125,
    fees: 0,
    currency: "AUD",
    platform: "Commsec Bank",
    assetClass: "Cash",
    notes: "Sam Thomas"
  },
  {
    id: "txn_000126",
    source: "initial_excel_import",
    sourceRow: 128,
    date: "2023-04-18",
    action: "Cash Deposit",
    assetTicker: "Cash",
    quantity: 1,
    price: 125,
    fees: 0,
    currency: "AUD",
    platform: "Commsec Bank",
    assetClass: "Cash",
    notes: "Tom Flitcroft"
  },
  {
    id: "txn_000127",
    source: "initial_excel_import",
    sourceRow: 129,
    date: "2023-04-25",
    action: "Buy",
    assetTicker: "ETH-AUD",
    quantity: 0.17704818,
    price: 2796.12874276,
    fees: 4.95,
    currency: "AUD",
    platform: "Coinbase",
    assetClass: "Crypto",
    sector: "Crypto",
    country: "Crypto World",
    strategy: "High Risk",
    notes: null
  },
  {
    id: "txn_000128",
    source: "initial_excel_import",
    sourceRow: 130,
    date: "2023-04-25",
    action: "Buy",
    assetTicker: "USDT-AUD",
    quantity: 0,
    price: 0,
    fees: 0,
    currency: "AUD",
    platform: "Coinbase",
    assetClass: "Crypto",
    sector: "Crypto",
    country: "Crypto World",
    strategy: "Low Risk",
    notes: null
  },
  {
    id: "txn_000129",
    source: "initial_excel_import",
    sourceRow: 131,
    date: "2023-04-25",
    action: "Cash Withdrawal",
    assetTicker: "Cash",
    quantity: 1,
    price: 500,
    fees: 0,
    currency: "AUD",
    platform: "Commsec Bank",
    assetClass: "Cash",
    notes: "Coin Spot"
  },
  {
    id: "txn_000130",
    source: "initial_excel_import",
    sourceRow: 132,
    date: "2023-05-01",
    action: "Cash Interest",
    assetTicker: "Interest",
    quantity: 1,
    price: 0.20,
    fees: 0,
    currency: "AUD",
    platform: "CDIA - Dividends",
    assetClass: "Cash",
    sector: "Others",
    country: "Australia",
    strategy: "Dividend",
    notes: null
  },
  {
    id: "txn_000131",
    source: "initial_excel_import",
    sourceRow: 133,
    date: "2023-05-14",
    action: "Cash Deposit",
    assetTicker: "Cash",
    quantity: 1,
    price: 125,
    fees: 0,
    currency: "AUD",
    platform: "Commsec Bank",
    assetClass: "Cash",
    notes: "Kieren Chan"
  },
  {
    id: "txn_000132",
    source: "initial_excel_import",
    sourceRow: 134,
    date: "2023-05-18",
    action: "Cash Deposit",
    assetTicker: "Cash",
    quantity: 1,
    price: 125,
    fees: 0,
    currency: "AUD",
    platform: "Commsec Bank",
    assetClass: "Cash",
    notes: "Sam Thomas"
  },
  {
    id: "txn_000133",
    source: "initial_excel_import",
    sourceRow: 135,
    date: "2023-05-18",
    action: "Cash Deposit",
    assetTicker: "Cash",
    quantity: 1,
    price: 125,
    fees: 0,
    currency: "AUD",
    platform: "Commsec Bank",
    assetClass: "Cash",
    notes: "Tom Flitcroft"
  }
];
