import type { SeedTransaction } from "../types";

export const transactions021: SeedTransaction[] = [
  {
    id: "txn_000204",
    source: "initial_excel_import",
    sourceRow: 206,
    date: "2024-06-01",
    action: "Cash Interest",
    assetTicker: "Interest",
    quantity: 1,
    price: 0.48,
    fees: 0,
    currency: "AUD",
    platform: "CDIA - Dividends",
    assetClass: "Cash",
    sector: "Others",
    country: "Australia",
    strategy: "Dividend",
    notes: null
  },
  {
    id: "txn_000205",
    source: "initial_excel_import",
    sourceRow: 207,
    date: "2024-06-13",
    action: "Cash Deposit",
    assetTicker: "Cash",
    quantity: 1,
    price: 125.00,
    fees: 0,
    currency: "AUD",
    platform: "Commsec Bank",
    assetClass: "Cash",
    notes: "Kieren Chan"
  },
  {
    id: "txn_000206",
    source: "initial_excel_import",
    sourceRow: 208,
    date: "2024-06-18",
    action: "Cash Deposit",
    assetTicker: "Cash",
    quantity: 1,
    price: 125.00,
    fees: 0,
    currency: "AUD",
    platform: "Commsec Bank",
    assetClass: "Cash",
    notes: "Sam Thomas"
  },
  {
    id: "txn_000207",
    source: "initial_excel_import",
    sourceRow: 209,
    date: "2024-06-19",
    action: "Cash Deposit",
    assetTicker: "Cash",
    quantity: 1,
    price: 125.00,
    fees: 0,
    currency: "AUD",
    platform: "Commsec Bank",
    assetClass: "Cash",
    notes: "Tom Flitcroft"
  },
  {
    id: "txn_000208",
    source: "initial_excel_import",
    sourceRow: 210,
    date: "2024-06-27",
    action: "Transfer Send",
    assetTicker: "Cash",
    quantity: 1,
    price: 2500.00,
    fees: 0,
    currency: "AUD",
    platform: "Commsec Shares",
    assetClass: "Cash",
    notes: "June Investment"
  },
  {
    id: "txn_000209",
    source: "initial_excel_import",
    sourceRow: 211,
    date: "2024-06-27",
    action: "Buy",
    assetTicker: "ASX:NAB",
    quantity: 33,
    price: 34.42,
    fees: 10,
    currency: "AUD",
    platform: "Commsec Shares",
    assetClass: "Stock",
    sector: "Financials",
    country: "Australia",
    strategy: "Low Risk",
    notes: "Dividend"
  },
  {
    id: "txn_000210",
    source: "initial_excel_import",
    sourceRow: 212,
    date: "2024-06-27",
    action: "Buy",
    assetTicker: "ASX:VAS",
    quantity: 10,
    price: 98.64,
    fees: 10,
    currency: "AUD",
    platform: "Commsec Shares",
    assetClass: "ETF",
    sector: "Diversified",
    country: "Australia",
    strategy: "Low Risk",
    notes: null
  },
  {
    id: "txn_000211",
    source: "initial_excel_import",
    sourceRow: 213,
    date: "2024-06-27",
    action: "Buy",
    assetTicker: "ASX:NDQ",
    quantity: 12,
    price: 47.86,
    fees: 10,
    currency: "AUD",
    platform: "Commsec Shares",
    assetClass: "ETF",
    sector: "Technology",
    country: "United States",
    strategy: "Medium Risk",
    notes: null
  },
  {
    id: "txn_000212",
    source: "initial_excel_import",
    sourceRow: 214,
    date: "2024-06-28",
    action: "Cash Dividend",
    assetTicker: "ASX:FMG",
    quantity: 1,
    price: 121.42,
    fees: 0,
    currency: "AUD",
    platform: "CDIA - Dividends",
    assetClass: "Stock",
    sector: "Materials",
    country: "Australia",
    strategy: "Dividend",
    notes: null
  },
  {
    id: "txn_000213",
    source: "initial_excel_import",
    sourceRow: 215,
    date: "2024-06-30",
    action: "Cash Interest",
    assetTicker: "Interest",
    quantity: 1,
    price: 0.53,
    fees: 0,
    currency: "AUD",
    platform: "CDIA - Dividends",
    assetClass: "Cash",
    sector: "Others",
    country: "Australia",
    strategy: "Dividend",
    notes: null
  }
];
