import type { SeedTransaction } from "../types";

export const transactions039: SeedTransaction[] = [
  {
    id: "txn_000384",
    source: "initial_excel_import",
    sourceRow: 376,
    date: "2025-08-18",
    action: "Cash Deposit",
    assetTicker: "Cash",
    quantity: 1,
    price: 150.00,
    fees: 0,
    currency: "AUD",
    platform: "Commsec Bank",
    assetClass: "Cash",
    notes: "Kieren Chan"
  },
  {
    id: "txn_000385",
    source: "initial_excel_import",
    sourceRow: 377,
    date: "2025-08-26",
    action: "Cash Dividend",
    assetTicker: "ASX:GMG",
    quantity: 1,
    price: 6.10,
    fees: 0,
    currency: "AUD",
    platform: "CDIA - Dividends",
    assetClass: "Stock",
    sector: "Real Estate",
    country: "Australia",
    strategy: "Dividend",
    notes: null
  },
  {
    id: "txn_000386",
    source: "initial_excel_import",
    sourceRow: 378,
    date: "2025-09-01",
    action: "Sell",
    assetTicker: "ETH-AUD",
    quantity: 0.37360193,
    price: 6732.03,
    fees: 23.422,
    currency: "AUD",
    platform: "Coinbase",
    assetClass: "Crypto",
    sector: "Crypto",
    country: "Crypto World",
    strategy: "High Risk",
    notes: "Agreed - 01 September 2025 Meeting"
  },
  {
    id: "txn_000387",
    source: "initial_excel_import",
    sourceRow: 379,
    date: "2025-09-01",
    action: "Sell",
    assetTicker: "SOL-AUD",
    quantity: 6.2639353,
    price: 304.37,
    fees: 19.04,
    currency: "AUD",
    platform: "Coinbase",
    assetClass: "Crypto",
    sector: "Crypto",
    country: "Crypto World",
    strategy: "High Risk",
    notes: "Agreed - 01 September 2025 Meeting"
  },
  {
    id: "txn_000388",
    source: "initial_excel_import",
    sourceRow: 380,
    date: "2025-09-01",
    action: "Cash Deposit",
    assetTicker: "Cash",
    quantity: 1,
    price: 4229.71,
    fees: 0,
    currency: "AUD",
    platform: "Commsec Bank",
    assetClass: "Cash",
    notes: "ETH AND SOL CASH"
  },
  {
    id: "txn_000389",
    source: "initial_excel_import",
    sourceRow: 381,
    date: "2025-09-01",
    action: "Cash Interest",
    assetTicker: "Interest",
    quantity: 1,
    price: 0.05,
    fees: 0,
    currency: "AUD",
    platform: "CDIA - Dividends",
    assetClass: "Cash",
    sector: "Others",
    country: "Australia",
    strategy: "Dividend",
    notes: null
  },
  {
    id: "txn_000390",
    source: "initial_excel_import",
    sourceRow: 382,
    date: "2025-09-05",
    action: "Buy",
    assetTicker: "VAS.AX",
    quantity: 14,
    price: 110.87,
    fees: 10,
    currency: "AUD",
    platform: "Commsec Shares",
    assetClass: "ETF",
    sector: "ETF",
    country: "Australia",
    strategy: "Low Risk",
    notes: null
  },
  {
    id: "txn_000391",
    source: "initial_excel_import",
    sourceRow: 383,
    date: "2025-09-15",
    action: "Cash Deposit",
    assetTicker: "Cash",
    quantity: 1,
    price: 175,
    fees: 0,
    currency: "AUD",
    platform: "Commsec Bank",
    assetClass: "Cash",
    notes: "Sam Thomas"
  },
  {
    id: "txn_000392",
    source: "initial_excel_import",
    sourceRow: 384,
    date: "2025-09-18",
    action: "Cash Deposit",
    assetTicker: "Cash",
    quantity: 1,
    price: 150,
    fees: 0,
    currency: "AUD",
    platform: "Commsec Bank",
    assetClass: "Cash",
    notes: "Tom Flitcroft"
  },
  {
    id: "txn_000393",
    source: "initial_excel_import",
    sourceRow: 385,
    date: "2025-09-19",
    action: "Cash Deposit",
    assetTicker: "Cash",
    quantity: 1,
    price: 175,
    fees: 0,
    currency: "AUD",
    platform: "Commsec Bank",
    assetClass: "Cash",
    notes: "Kieren Chan"
  }
];
