import type { SeedTransaction } from "../types";

export const transactions015: SeedTransaction[] = [
  {
    id: "txn_000144",
    source: "initial_excel_import",
    sourceRow: 146,
    date: "2023-06-28",
    action: "Buy",
    assetTicker: "ASX:NAB",
    quantity: 37,
    price: 26.23,
    fees: 10,
    currency: "AUD",
    platform: "Commsec Shares",
    assetClass: "Stock",
    sector: "Financials",
    country: "Australia",
    strategy: "Low Risk",
    notes: null
  },
  {
    id: "txn_000145",
    source: "initial_excel_import",
    sourceRow: 147,
    date: "2023-06-28",
    action: "Buy",
    assetTicker: "ASX:LGP",
    quantity: 3000,
    price: 0.17,
    fees: 10,
    currency: "AUD",
    platform: "Commsec Shares",
    assetClass: "Stock",
    sector: "Healthcare",
    country: "Australia",
    strategy: "Low Risk",
    notes: null
  },
  {
    id: "txn_000146",
    source: "initial_excel_import",
    sourceRow: 148,
    date: "2023-06-28",
    action: "Buy",
    assetTicker: "ASX:RFG",
    quantity: 250.1492537,
    price: 0.05,
    fees: 10,
    currency: "AUD",
    platform: "Commsec Shares",
    assetClass: "Stock",
    sector: "Consumer Discretionary",
    country: "Australia",
    strategy: "High Risk",
    notes: null
  },
  {
    id: "txn_000147",
    source: "initial_excel_import",
    sourceRow: 149,
    date: "2023-06-30",
    action: "Cash Withdrawal",
    assetTicker: "Cash",
    quantity: 1,
    price: 1000,
    fees: 0,
    currency: "AUD",
    platform: "Commsec Bank",
    assetClass: "Cash",
    notes: "Coin Spot"
  },
  {
    id: "txn_000148",
    source: "initial_excel_import",
    sourceRow: 150,
    date: "2023-07-01",
    action: "Cash Interest",
    assetTicker: "Interest",
    quantity: 1,
    price: 0.26,
    fees: 0,
    currency: "AUD",
    platform: "CDIA - Dividends",
    assetClass: "Cash",
    sector: "Others",
    country: "Australia",
    strategy: "Dividend",
    notes: null
  },
  {
    id: "txn_000149",
    source: "initial_excel_import",
    sourceRow: 151,
    date: "2023-07-14",
    action: "Cash Deposit",
    assetTicker: "Cash",
    quantity: 1,
    price: 125,
    fees: 0,
    currency: "AUD",
    platform: "Commsec Bank",
    assetClass: "Cash",
    notes: "Kieren Chan"
  },
  {
    id: "txn_000150",
    source: "initial_excel_import",
    sourceRow: 152,
    date: "2023-07-17",
    action: "Cash Dividend",
    assetTicker: "ASX:SEMI",
    quantity: 1,
    price: 2.08,
    fees: 0,
    currency: "AUD",
    platform: "CDIA - Dividends",
    assetClass: "Stock",
    sector: "Others",
    country: "Australia",
    strategy: "Dividend",
    notes: null
  },
  {
    id: "txn_000151",
    source: "initial_excel_import",
    sourceRow: 153,
    date: "2023-07-18",
    action: "Cash Deposit",
    assetTicker: "Cash",
    quantity: 1,
    price: 125,
    fees: 0,
    currency: "AUD",
    platform: "Commsec Bank",
    assetClass: "Cash",
    notes: "Sam Thomas"
  },
  {
    id: "txn_000152",
    source: "initial_excel_import",
    sourceRow: 154,
    date: "2023-07-18",
    action: "Cash Deposit",
    assetTicker: "Cash",
    quantity: 1,
    price: 125,
    fees: 0,
    currency: "AUD",
    platform: "Commsec Bank",
    assetClass: "Cash",
    notes: "Tom Flitcroft"
  },
  {
    id: "txn_000153",
    source: "initial_excel_import",
    sourceRow: 155,
    date: "2023-08-01",
    action: "Cash Interest",
    assetTicker: "Interest",
    quantity: 1,
    price: 0.05,
    fees: 0,
    currency: "AUD",
    platform: "CDIA - Dividends",
    assetClass: "Cash",
    sector: "Others",
    country: "Australia",
    strategy: "Dividend",
    notes: null
  }
];
