import type { SeedTransaction } from "../types";

export const transactions043: SeedTransaction[] = [
  {
    id: "txn_000424",
    source: "initial_excel_import",
    sourceRow: 416,
    date: "2026-01-01",
    action: "Cash Interest",
    assetTicker: "Interest",
    quantity: 1,
    price: 0.04,
    fees: 0,
    currency: "AUD",
    platform: "Commsec Bank",
    assetClass: "Cash",
    sector: "Others",
    country: "Australia",
    strategy: "Dividend",
    notes: null
  },
  {
    id: "txn_000425",
    source: "initial_excel_import",
    sourceRow: 417,
    date: "2026-01-15",
    action: "Cash Deposit",
    assetTicker: "Cash",
    quantity: 1,
    price: 175.00,
    fees: 0,
    currency: "AUD",
    platform: "Commsec Bank",
    assetClass: "Cash",
    notes: "Kieren Chan"
  },
  {
    id: "txn_000426",
    source: "initial_excel_import",
    sourceRow: 418,
    date: "2026-01-16",
    action: "Cash Deposit",
    assetTicker: "Cash",
    quantity: 1,
    price: 175.00,
    fees: 0,
    currency: "AUD",
    platform: "Commsec Bank",
    assetClass: "Cash",
    notes: "Sam Thomas"
  },
  {
    id: "txn_000427",
    source: "initial_excel_import",
    sourceRow: 419,
    date: "2026-01-19",
    action: "Cash Deposit",
    assetTicker: "Cash",
    quantity: 1,
    price: 175.00,
    fees: 0,
    currency: "AUD",
    platform: "Commsec Bank",
    assetClass: "Cash",
    notes: "Tom Flitcroft"
  },
  {
    id: "txn_000428",
    source: "initial_excel_import",
    sourceRow: 420,
    date: "2026-01-20",
    action: "Cash Dividend",
    assetTicker: "VAS.AX",
    quantity: 1,
    price: 7.81,
    fees: 0,
    currency: "AUD",
    platform: "CDIA - Dividends",
    assetClass: "ETF",
    sector: "ETF",
    country: "Australia",
    strategy: "Dividend",
    notes: null
  },
  {
    id: "txn_000429",
    source: "initial_excel_import",
    sourceRow: 421,
    date: "2026-01-21",
    action: "Cash Dividend",
    assetTicker: "ASX:SEMI",
    quantity: 1,
    price: 74.52,
    fees: 0,
    currency: "AUD",
    platform: "CDIA - Dividends",
    assetClass: "ETF",
    sector: "Technology",
    country: "Australia",
    strategy: "Dividend",
    notes: null
  },
  {
    id: "txn_000430",
    source: "initial_excel_import",
    sourceRow: 422,
    date: "2026-01-27",
    action: "Cash Dividend",
    assetTicker: "NYSE:ALB",
    quantity: 1,
    price: 5.81,
    fees: 0,
    currency: "USD",
    platform: "Commsec International Shares",
    assetClass: "Stock",
    sector: "Materials",
    country: "United States",
    strategy: "Dividend",
    notes: null
  },
  {
    id: "txn_000431",
    source: "initial_excel_import",
    sourceRow: 423,
    date: "2026-02-01",
    action: "Cash Interest",
    assetTicker: "Interest",
    quantity: 1,
    price: 0.05,
    fees: 0,
    currency: "AUD",
    platform: "Commsec Bank",
    assetClass: "Cash",
    sector: "Others",
    country: "Australia",
    strategy: "Dividend",
    notes: null
  },
  {
    id: "txn_000432",
    source: "initial_excel_import",
    sourceRow: 424,
    date: "2026-02-16",
    action: "Cash Deposit",
    assetTicker: "Cash",
    quantity: 1,
    price: 175.00,
    fees: 0,
    currency: "AUD",
    platform: "Commsec Bank",
    assetClass: "Cash",
    notes: "Kieren Chan"
  },
  {
    id: "txn_000433",
    source: "initial_excel_import",
    sourceRow: 425,
    date: "2026-02-17",
    action: "Cash Deposit",
    assetTicker: "Cash",
    quantity: 1,
    price: 175.00,
    fees: 0,
    currency: "AUD",
    platform: "Commsec Bank",
    assetClass: "Cash",
    notes: "Sam Thomas"
  }
];
