import type { SeedTransaction } from "../types";

export const transactions019: SeedTransaction[] = [
  {
    id: "txn_000184",
    source: "initial_excel_import",
    sourceRow: 186,
    date: "2024-02-01",
    action: "Cash Interest",
    assetTicker: "Interest",
    quantity: 1,
    price: 0.31,
    fees: 0,
    currency: "AUD",
    platform: "CDIA - Dividends",
    assetClass: "Cash",
    sector: "Others",
    country: "Australia",
    strategy: "Dividend",
    notes: null
  },
  {
    id: "txn_000185",
    source: "initial_excel_import",
    sourceRow: 187,
    date: "2024-02-14",
    action: "Cash Deposit",
    assetTicker: "Cash",
    quantity: 1,
    price: 125.00,
    fees: 0,
    currency: "AUD",
    platform: "Commsec Bank",
    assetClass: "Cash",
    notes: "Kieren Chan"
  },
  {
    id: "txn_000186",
    source: "initial_excel_import",
    sourceRow: 188,
    date: "2024-02-16",
    action: "Cash Deposit",
    assetTicker: "Cash",
    quantity: 1,
    price: 125.00,
    fees: 0,
    currency: "AUD",
    platform: "Commsec Bank",
    assetClass: "Cash",
    notes: "Sam Thomas"
  },
  {
    id: "txn_000187",
    source: "initial_excel_import",
    sourceRow: 189,
    date: "2024-02-19",
    action: "Cash Deposit",
    assetTicker: "Cash",
    quantity: 1,
    price: 125.00,
    fees: 0,
    currency: "AUD",
    platform: "Commsec Bank",
    assetClass: "Cash",
    notes: "Tom Flitcroft"
  },
  {
    id: "txn_000188",
    source: "initial_excel_import",
    sourceRow: 190,
    date: "2024-02-26",
    action: "Cash Dividend",
    assetTicker: "ASX:GMG",
    quantity: 1,
    price: 7.48,
    fees: 0,
    currency: "AUD",
    platform: "CDIA - Dividends",
    assetClass: "Stock",
    sector: "Real Estate",
    country: "Australia",
    strategy: "Dividend",
    notes: null
  },
  {
    id: "txn_000189",
    source: "initial_excel_import",
    sourceRow: 191,
    date: "2024-03-01",
    action: "Cash Interest",
    assetTicker: "Interest",
    quantity: 1,
    price: 0.42,
    fees: 0,
    currency: "AUD",
    platform: "CDIA - Dividends",
    assetClass: "Cash",
    sector: "Others",
    country: "Australia",
    strategy: "Dividend",
    notes: null
  },
  {
    id: "txn_000190",
    source: "initial_excel_import",
    sourceRow: 192,
    date: "2024-03-15",
    action: "Cash Deposit",
    assetTicker: "Cash",
    quantity: 1,
    price: 125.00,
    fees: 0,
    currency: "AUD",
    platform: "Commsec Bank",
    assetClass: "Cash",
    notes: "Kieren Chan"
  },
  {
    id: "txn_000191",
    source: "initial_excel_import",
    sourceRow: 193,
    date: "2024-03-20",
    action: "Cash Dividend",
    assetTicker: "ASX:EDV",
    quantity: 1,
    price: 22.34,
    fees: 0,
    currency: "AUD",
    platform: "CDIA - Dividends",
    assetClass: "Stock",
    sector: "Consumer Staples",
    country: "Australia",
    strategy: "Dividend",
    notes: null
  },
  {
    id: "txn_000192",
    source: "initial_excel_import",
    sourceRow: 194,
    date: "2024-03-28",
    action: "Cash Dividend",
    assetTicker: "ASX:FMG",
    quantity: 1,
    price: 118.76,
    fees: 0,
    currency: "AUD",
    platform: "CDIA - Dividends",
    assetClass: "Stock",
    sector: "Materials",
    country: "Australia",
    strategy: "Dividend",
    notes: null
  },
  {
    id: "txn_000193",
    source: "initial_excel_import",
    sourceRow: 195,
    date: "2024-03-31",
    action: "Cash Interest",
    assetTicker: "Interest",
    quantity: 1,
    price: 0.38,
    fees: 0,
    currency: "AUD",
    platform: "CDIA - Dividends",
    assetClass: "Cash",
    sector: "Others",
    country: "Australia",
    strategy: "Dividend",
    notes: null
  }
];
