import type { SeedTransaction } from "../types";

export const transactions017: SeedTransaction[] = [
  {
    id: "txn_000164",
    source: "initial_excel_import",
    sourceRow: 166,
    date: "2023-09-27",
    action: "Cash Dividend",
    assetTicker: "ASX:EDV",
    quantity: 1,
    price: 11.33,
    fees: 0,
    currency: "AUD",
    platform: "CDIA - Dividends",
    assetClass: "Stock",
    sector: "Consumer Staples",
    country: "Australia",
    strategy: "Dividend",
    notes: null
  },
  {
    id: "txn_000165",
    source: "initial_excel_import",
    sourceRow: 167,
    date: "2023-09-28",
    action: "Cash Dividend",
    assetTicker: "ASX:FMG",
    quantity: 1,
    price: 106.00,
    fees: 0,
    currency: "AUD",
    platform: "CDIA - Dividends",
    assetClass: "Stock",
    sector: "Materials",
    country: "Australia",
    strategy: "Dividend",
    notes: null
  },
  {
    id: "txn_000166",
    source: "initial_excel_import",
    sourceRow: 168,
    date: "2023-10-01",
    action: "Cash Interest",
    assetTicker: "Interest",
    quantity: 1,
    price: 0.06,
    fees: 0,
    currency: "AUD",
    platform: "CDIA - Dividends",
    assetClass: "Cash",
    sector: "Others",
    country: "Australia",
    strategy: "Dividend",
    notes: null
  },
  {
    id: "txn_000167",
    source: "initial_excel_import",
    sourceRow: 169,
    date: "2023-10-10",
    action: "Cash Deposit",
    assetTicker: "Cash",
    quantity: 1,
    price: 125.00,
    fees: 0,
    currency: "AUD",
    platform: "Commsec Bank",
    assetClass: "Cash",
    notes: null
  },
  {
    id: "txn_000168",
    source: "initial_excel_import",
    sourceRow: 170,
    date: "2023-10-18",
    action: "Cash Deposit",
    assetTicker: "Cash",
    quantity: 1,
    price: 125.00,
    fees: 0,
    currency: "AUD",
    platform: "Commsec Bank",
    assetClass: "Cash",
    notes: null
  },
  {
    id: "txn_000169",
    source: "initial_excel_import",
    sourceRow: 171,
    date: "2023-10-18",
    action: "Cash Deposit",
    assetTicker: "Cash",
    quantity: 1,
    price: 125.00,
    fees: 0,
    currency: "AUD",
    platform: "Commsec Bank",
    assetClass: "Cash",
    notes: null
  },
  {
    id: "txn_000170",
    source: "initial_excel_import",
    sourceRow: 172,
    date: "2023-11-01",
    action: "Cash Interest",
    assetTicker: "Interest",
    quantity: 1,
    price: 0.11,
    fees: 0,
    currency: "AUD",
    platform: "CDIA - Dividends",
    assetClass: "Cash",
    sector: "Others",
    country: "Australia",
    strategy: "Dividend",
    notes: null
  },
  {
    id: "txn_000171",
    source: "initial_excel_import",
    sourceRow: 173,
    date: "2023-11-18",
    action: "Cash Deposit",
    assetTicker: "Cash",
    quantity: 1,
    price: 125.00,
    fees: 0,
    currency: "AUD",
    platform: "Commsec Bank",
    assetClass: "Cash",
    notes: null
  },
  {
    id: "txn_000172",
    source: "initial_excel_import",
    sourceRow: 174,
    date: "2023-11-20",
    action: "Cash Deposit",
    assetTicker: "Cash",
    quantity: 1,
    price: 125.00,
    fees: 0,
    currency: "AUD",
    platform: "Commsec Bank",
    assetClass: "Cash",
    notes: null
  },
  {
    id: "txn_000173",
    source: "initial_excel_import",
    sourceRow: 175,
    date: "2023-11-21",
    action: "Cash Deposit",
    assetTicker: "Cash",
    quantity: 1,
    price: 125.00,
    fees: 0,
    currency: "AUD",
    platform: "Commsec Bank",
    assetClass: "Cash",
    notes: null
  }
];
