import type { SeedTransaction } from "../types";

export const transactions036: SeedTransaction[] = [
  {
    id: "txn_000354",
    source: "initial_excel_import",
    sourceRow: 346,
    date: "2025-07-17",
    action: "Cash Deposit",
    assetTicker: "Cash",
    quantity: 1,
    price: 150.00,
    fees: 0,
    currency: "AUD",
    platform: "Commsec Bank",
    assetClass: "Cash",
    notes: "Sam Thomas"
  },
  {
    id: "txn_000355",
    source: "initial_excel_import",
    sourceRow: 347,
    date: "2025-07-18",
    action: "Cash Deposit",
    assetTicker: "Cash",
    quantity: 1,
    price: 150.00,
    fees: 0,
    currency: "AUD",
    platform: "Commsec Bank",
    assetClass: "Cash",
    notes: "Kieren Chan"
  },
  {
    id: "txn_000356",
    source: "initial_excel_import",
    sourceRow: 348,
    date: "2025-07-18",
    action: "Cash Deposit",
    assetTicker: "Cash",
    quantity: 1,
    price: 150.00,
    fees: 0,
    currency: "AUD",
    platform: "Commsec Bank",
    assetClass: "Cash",
    notes: "Tom Flitcroft"
  },
  {
    id: "txn_000357",
    source: "initial_excel_import",
    sourceRow: 349,
    date: "2025-07-22",
    action: "Sell",
    assetTicker: "ETH-AUD",
    quantity: 0.2997,
    price: 5720.33,
    fees: 17.14382901,
    currency: "AUD",
    platform: "Coinbase",
    assetClass: "Crypto",
    sector: "Crypto",
    country: "Crypto World",
    strategy: "High Risk",
    notes: null
  },
  {
    id: "txn_000358",
    source: "initial_excel_import",
    sourceRow: 350,
    date: "2025-07-22",
    action: "Transfer Deposit",
    assetTicker: "Cash",
    quantity: 1,
    price: 1697.24,
    fees: 0,
    currency: "AUD",
    platform: "Commsec Bank",
    assetClass: "Cash",
    notes: "ETH Profits"
  },
  {
    id: "txn_000359",
    source: "initial_excel_import",
    sourceRow: 351,
    date: "2025-07-26",
    action: "Sell",
    assetTicker: "BNB-AUD",
    quantity: 0.109,
    price: 1191.78,
    fees: 1.2990402,
    currency: "AUD",
    platform: "Coinbase",
    assetClass: "Crypto",
    sector: "Crypto",
    country: "Crypto World",
    strategy: "High Risk",
    notes: null
  },
  {
    id: "txn_000360",
    source: "initial_excel_import",
    sourceRow: 352,
    date: "2025-07-27",
    action: "Cash Deposit",
    assetTicker: "Cash",
    quantity: 1,
    price: 128.61,
    fees: 0,
    currency: "AUD",
    platform: "Commsec Bank",
    assetClass: "Cash",
    notes: "BNB Profits"
  },
  {
    id: "txn_000361",
    source: "initial_excel_import",
    sourceRow: 353,
    date: "2025-07-28",
    action: "Cash Deposit",
    assetTicker: "Cash",
    quantity: 1,
    price: 3403.55,
    fees: 0,
    currency: "AUD",
    platform: "Commsec Bank",
    assetClass: "Cash",
    notes: "Rebalance"
  },
  {
    id: "txn_000362",
    source: "initial_excel_import",
    sourceRow: 354,
    date: "2025-07-28",
    action: "Cash Deposit",
    assetTicker: "Cash",
    quantity: 1,
    price: 401.50,
    fees: 0,
    currency: "AUD",
    platform: "Commsec Bank",
    assetClass: "Cash",
    notes: "Rebalance - TBC"
  },
  {
    id: "txn_000363",
    source: "initial_excel_import",
    sourceRow: 355,
    date: "2025-07-28",
    action: "Cash Withdrawal",
    assetTicker: "Cash",
    quantity: 1,
    price: 3305.16,
    fees: 0,
    currency: "AUD",
    platform: "Commsec Bank",
    assetClass: "Cash",
    notes: "Rebalance"
  }
];
