import type { SeedTransaction } from "../types";

export const transactions006: SeedTransaction[] = [
  {
    id: "txn_000054",
    source: "initial_excel_import",
    sourceRow: 56,
    date: "2022-02-20",
    action: "Cash Deposit",
    assetTicker: "Cash",
    quantity: 1,
    price: 125,
    fees: 0,
    currency: "AUD",
    platform: "Commsec Bank",
    assetClass: "Cash",
    notes: "Marc Mario"
  },
  {
    id: "txn_000055",
    source: "initial_excel_import",
    sourceRow: 57,
    date: "2022-02-20",
    action: "Cash Deposit",
    assetTicker: "Cash",
    quantity: 1,
    price: 125,
    fees: 0,
    currency: "AUD",
    platform: "Commsec Bank",
    assetClass: "Cash",
    notes: "Sam Thomas"
  },
  {
    id: "txn_000056",
    source: "initial_excel_import",
    sourceRow: 58,
    date: "2022-02-22",
    action: "Cash Deposit",
    assetTicker: "Cash",
    quantity: 1,
    price: 125,
    fees: 0,
    currency: "AUD",
    platform: "Commsec Bank",
    assetClass: "Cash",
    notes: "Tom Flitcroft"
  },
  {
    id: "txn_000057",
    source: "initial_excel_import",
    sourceRow: 59,
    date: "2022-02-24",
    action: "Buy",
    assetTicker: "ETH-AUD",
    quantity: 0.09831441,
    price: 2352.90,
    fees: 4.95,
    currency: "AUD",
    platform: "Coinbase",
    assetClass: "Crypto",
    sector: "Crypto",
    country: "Crypto World",
    strategy: "High Risk"
  },
  {
    id: "txn_000058",
    source: "initial_excel_import",
    sourceRow: 60,
    date: "2022-03-14",
    action: "Cash Deposit",
    assetTicker: "Cash",
    quantity: 1,
    price: 125,
    fees: 0,
    currency: "AUD",
    platform: "Commsec Bank",
    assetClass: "Cash",
    notes: "Kieren Chan"
  },
  {
    id: "txn_000059",
    source: "initial_excel_import",
    sourceRow: 61,
    date: "2022-03-19",
    action: "Cash Deposit",
    assetTicker: "Cash",
    quantity: 1,
    price: 125,
    fees: 0,
    currency: "AUD",
    platform: "Commsec Bank",
    assetClass: "Cash",
    notes: "Sam Thomas"
  },
  {
    id: "txn_000060",
    source: "initial_excel_import",
    sourceRow: 62,
    date: "2022-03-26",
    action: "Cash Deposit",
    assetTicker: "Cash",
    quantity: 1,
    price: 125,
    fees: 0,
    currency: "AUD",
    platform: "Commsec Bank",
    assetClass: "Cash",
    notes: "Marc Mario"
  },
  {
    id: "txn_000061",
    source: "initial_excel_import",
    sourceRow: 63,
    date: "2022-03-28",
    action: "Cash Withdrawal",
    assetTicker: "Cash",
    quantity: 1,
    price: 88,
    fees: 0,
    currency: "AUD",
    platform: "Commsec Bank",
    assetClass: "Cash",
    notes: "Business Name"
  },
  {
    id: "txn_000062",
    source: "initial_excel_import",
    sourceRow: 64,
    date: "2022-03-28",
    action: "Cash Dividend",
    assetTicker: "ASX:EDV",
    quantity: 1,
    price: 18.88,
    fees: 0,
    currency: "AUD",
    platform: "CDIA - Dividends",
    assetClass: "Stock",
    sector: "Consumer Staples",
    country: "Australia",
    strategy: "Dividend"
  },
  {
    id: "txn_000063",
    source: "initial_excel_import",
    sourceRow: 65,
    date: "2022-03-29",
    action: "Cash Deposit",
    assetTicker: "Cash",
    quantity: 1,
    price: 125,
    fees: 0,
    currency: "AUD",
    platform: "Commsec Bank",
    assetClass: "Cash",
    notes: "Tom Flitcroft"
  }
];
