import type { SeedTransaction } from "../types";

export const transactions041: SeedTransaction[] = [
  {
    id: "txn_000404",
    source: "initial_excel_import",
    sourceRow: 396,
    date: "2025-10-15",
    action: "Cash Dividend",
    assetTicker: "VAS.AX",
    quantity: 1,
    price: 7.43,
    fees: 0,
    currency: "AUD",
    platform: "CDIA - Dividends",
    assetClass: "ETF",
    sector: "ETF",
    country: "Australia",
    strategy: "Dividend",
    notes: null
  },
  {
    id: "txn_000405",
    source: "initial_excel_import",
    sourceRow: 397,
    date: "2025-10-16",
    action: "Cash Dividend",
    assetTicker: "ASX:SEMI",
    quantity: 1,
    price: 70.82,
    fees: 0,
    currency: "AUD",
    platform: "CDIA - Dividends",
    assetClass: "ETF",
    sector: "Technology",
    country: "Australia",
    strategy: "Dividend",
    notes: null
  },
  {
    id: "txn_000406",
    source: "initial_excel_import",
    sourceRow: 398,
    date: "2025-10-20",
    action: "Cash Deposit",
    assetTicker: "Cash",
    quantity: 1,
    price: 175.00,
    fees: 0,
    currency: "AUD",
    platform: "Commsec Bank",
    assetClass: "Cash",
    notes: "Kieren Chan"
  },
  {
    id: "txn_000407",
    source: "initial_excel_import",
    sourceRow: 399,
    date: "2025-10-21",
    action: "Cash Deposit",
    assetTicker: "Cash",
    quantity: 1,
    price: 175.00,
    fees: 0,
    currency: "AUD",
    platform: "Commsec Bank",
    assetClass: "Cash",
    notes: "Sam Thomas"
  },
  {
    id: "txn_000408",
    source: "initial_excel_import",
    sourceRow: 400,
    date: "2025-10-22",
    action: "Cash Deposit",
    assetTicker: "Cash",
    quantity: 1,
    price: 175.00,
    fees: 0,
    currency: "AUD",
    platform: "Commsec Bank",
    assetClass: "Cash",
    notes: "Tom Flitcroft"
  },
  {
    id: "txn_000409",
    source: "initial_excel_import",
    sourceRow: 401,
    date: "2025-10-27",
    action: "Cash Dividend",
    assetTicker: "NYSE:ALB",
    quantity: 1,
    price: 5.47,
    fees: 0,
    currency: "USD",
    platform: "Commsec International Shares",
    assetClass: "Stock",
    sector: "Materials",
    country: "United States",
    strategy: "Dividend",
    notes: null
  },
  {
    id: "txn_000410",
    source: "initial_excel_import",
    sourceRow: 402,
    date: "2025-11-01",
    action: "Cash Interest",
    assetTicker: "Interest",
    quantity: 1,
    price: 0.03,
    fees: 0,
    currency: "AUD",
    platform: "CDIA - Dividends",
    assetClass: "Cash",
    sector: "Others",
    country: "Australia",
    strategy: "Dividend",
    notes: null
  },
  {
    id: "txn_000411",
    source: "initial_excel_import",
    sourceRow: 403,
    date: "2025-11-14",
    action: "Cash Deposit",
    assetTicker: "Cash",
    quantity: 1,
    price: 175.00,
    fees: 0,
    currency: "AUD",
    platform: "Commsec Bank",
    assetClass: "Cash",
    notes: "Kieren Chan"
  },
  {
    id: "txn_000412",
    source: "initial_excel_import",
    sourceRow: 404,
    date: "2025-11-17",
    action: "Cash Deposit",
    assetTicker: "Cash",
    quantity: 1,
    price: 175.00,
    fees: 0,
    currency: "AUD",
    platform: "Commsec Bank",
    assetClass: "Cash",
    notes: "Sam Thomas"
  },
  {
    id: "txn_000413",
    source: "initial_excel_import",
    sourceRow: 405,
    date: "2025-11-18",
    action: "Cash Deposit",
    assetTicker: "Cash",
    quantity: 1,
    price: 175.00,
    fees: 0,
    currency: "AUD",
    platform: "Commsec Bank",
    assetClass: "Cash",
    notes: "Tom Flitcroft"
  }
];
