import type { Transaction } from "./types";

export const transactions: Transaction[] = [
  {
    id: "TX001",
    date: "2026-07-01",
    account: "Main Portfolio",
    broker: "CommSec",
    symbol: "VAS",
    company: "Vanguard Australian Shares ETF",
    type: "Buy",
    quantity: 12,
    price: 97.44,
    fees: 9.5,
    total: 1178.78,
    currency: "AUD",
  },
  {
    id: "TX002",
    date: "2026-07-02",
    account: "ETF Builder",
    broker: "CommSec Pocket",
    symbol: "NDQ",
    company: "Betashares Nasdaq 100 ETF",
    type: "Buy",
    quantity: 10,
    price: 47.88,
    fees: 0,
    total: 478.8,
    currency: "AUD",
  },
  {
    id: "TX003",
    date: "2026-07-03",
    account: "Main Portfolio",
    broker: "CommSec",
    symbol: "NAB",
    company: "National Australia Bank",
    type: "Dividend",
    quantity: 0,
    price: 0,
    fees: 0,
    total: 372.30,
    currency: "AUD",
  },
];
