import type { HoldingAccount, HoldingRow } from "./types";

export const holdingAccounts: HoldingAccount[] = [
  {
    id: "all",
    name: "All Accounts",
    broker: "Combined",
  },
  {
    id: "main",
    name: "Main Portfolio",
    broker: "CommSec",
  },
  {
    id: "etf-builder",
    name: "ETF Builder",
    broker: "CommSec Pocket",
  },
  {
    id: "baby",
    name: "Baby Portfolio",
    broker: "Long Term",
  },
];

export const holdingRows: HoldingRow[] = [
  {
    id: "1",
    accountId: "main",
    symbol: "VAS",
    name: "Vanguard Australian Shares ETF",
    exchange: "ASX",
    assetClass: "ETF",
    sector: "Broad Market",
    currency: "AUD",
    quantity: 280,
    averagePrice: 89.12,
    currentPrice: 97.44,
    marketValue: 27283.2,
    costBase: 24953.6,
    unrealisedPnl: 2329.6,
    unrealisedPnlPercent: 9.34,
    portfolioWeight: 21.25,
  },
  {
    id: "2",
    accountId: "etf-builder",
    symbol: "NDQ",
    name: "BetaShares Nasdaq 100 ETF",
    exchange: "ASX",
    assetClass: "ETF",
    sector: "Technology",
    currency: "AUD",
    quantity: 420,
    averagePrice: 39.2,
    currentPrice: 47.88,
    marketValue: 20109.6,
    costBase: 16464,
    unrealisedPnl: 3645.6,
    unrealisedPnlPercent: 22.14,
    portfolioWeight: 15.66,
  },
  {
    id: "3",
    accountId: "main",
    symbol: "NAB",
    name: "National Australia Bank",
    exchange: "ASX",
    assetClass: "Share",
    sector: "Financials",
    currency: "AUD",
    quantity: 510,
    averagePrice: 31.8,
    currentPrice: 37.26,
    marketValue: 19002.6,
    costBase: 16218,
    unrealisedPnl: 2784.6,
    unrealisedPnlPercent: 17.17,
    portfolioWeight: 14.8,
  },
  {
    id: "4",
    accountId: "main",
    symbol: "COH",
    name: "Cochlear Limited",
    exchange: "ASX",
    assetClass: "Share",
    sector: "Healthcare",
    currency: "AUD",
    quantity: 34,
    averagePrice: 286.4,
    currentPrice: 314.12,
    marketValue: 10680.08,
    costBase: 9737.6,
    unrealisedPnl: 942.48,
    unrealisedPnlPercent: 9.68,
    portfolioWeight: 8.32,
  },
];
