import type { SeedTransaction } from "../types";

export const transactions026: SeedTransaction[] = [
  {
    id: "txn_000254",
    source: "initial_excel_import",
    sourceRow: 246,
    date: "2024-06-28",
    action: "Buy",
    assetTicker: "ASX:WDS",
    quantity: 18,
    price: 28.45,
    fees: 4.99,
    currency: "AUD",
    platform: "Commsec Shares",
    assetClass: "Stock",
    sector: "Energy",
    country: "Australia",
    strategy: "High Risk",
    notes: null
  },
  {
    id: "txn_000255",
    source: "initial_excel_import",
    sourceRow: 247,
    date: "2024-07-01",
    action: "Cash Interest",
    assetTicker: "Interest",
    quantity: 1,
    price: 0.10,
    fees: 0,
    currency: "AUD",
    platform: "CDIA - Dividends",
    assetClass: "Cash",
    sector: "Others",
    country: "Australia",
    strategy: "Dividend",
    notes: null
  },
  {
    id: "txn_000256",
    source: "initial_excel_import",
    sourceRow: 248,
    date: "2024-07-02",
    action: "Cash Deposit",
    assetTicker: "Cash",
    quantity: 1,
    price: 125.00,
    fees: 0,
    currency: "AUD",
    platform: "Commsec Bank",
    assetClass: "Cash",
    notes: "Kieren Chan"
  },
  {
    id: "txn_000257",
    source: "initial_excel_import",
    sourceRow: 249,
    date: "2024-07-03",
    action: "Cash Dividend",
    assetTicker: "ASX:NAB",
    quantity: 1,
    price: 31.08,
    fees: 0,
    currency: "AUD",
    platform: "CDIA - Dividends",
    assetClass: "Stock",
    sector: "Financials",
    country: "Australia",
    strategy: "Dividend",
    notes: null
  },
  {
    id: "txn_000258",
    source: "initial_excel_import",
    sourceRow: 250,
    date: "2024-07-16",
    action: "Cash Dividend",
    assetTicker: "VAS.AX",
    quantity: 1,
    price: 3.03,
    fees: 0,
    currency: "AUD",
    platform: "CDIA - Dividends",
    assetClass: "ETF",
    sector: "ETF",
    country: "Australia",
    strategy: "Dividend",
    notes: null
  },
  {
    id: "txn_000259",
    source: "initial_excel_import",
    sourceRow: 251,
    date: "2024-07-16",
    action: "Cash Dividend",
    assetTicker: "ASX:SEMI",
    quantity: 1,
    price: 28.59,
    fees: 0,
    currency: "AUD",
    platform: "CDIA - Dividends",
    assetClass: "Stock",
    sector: "Others",
    country: "Australia",
    strategy: "Dividend",
    notes: null
  },
  {
    id: "txn_000260",
    source: "initial_excel_import",
    sourceRow: 252,
    date: "2024-07-18",
    action: "Cash Deposit",
    assetTicker: "Cash",
    quantity: 1,
    price: 125.00,
    fees: 0,
    currency: "AUD",
    platform: "Commsec Bank",
    assetClass: "Cash",
    notes: "Tom Flitcroft"
  },
  {
    id: "txn_000261",
    source: "initial_excel_import",
    sourceRow: 253,
    date: "2024-07-19",
    action: "Cash Deposit",
    assetTicker: "Cash",
    quantity: 1,
    price: 125.00,
    fees: 0,
    currency: "AUD",
    platform: "Commsec Bank",
    assetClass: "Cash",
    notes: "Sam Thomas"
  },
  {
    id: "txn_000262",
    source: "initial_excel_import",
    sourceRow: 254,
    date: "2024-07-19",
    action: "Cash Deposit",
    assetTicker: "Cash",
    quantity: 1,
    price: 125.00,
    fees: 0,
    currency: "AUD",
    platform: "Commsec Bank",
    assetClass: "Cash",
    notes: "Tom Flitcroft"
  },
  {
    id: "txn_000263",
    source: "initial_excel_import",
    sourceRow: 255,
    date: "2024-08-01",
    action: "Cash Deposit",
    assetTicker: "Cash",
    quantity: 1,
    price: 125.00,
    fees: 0,
    currency: "AUD",
    platform: "Commsec Bank",
    assetClass: "Cash",
    notes: "Kieren Chan"
  }
];
