import type { SeedTransaction } from "../types";

export const transactions031: SeedTransaction[] = [
  {
    id: "txn_000304",
    source: "initial_excel_import",
    sourceRow: 296,
    date: "2024-12-27",
    action: "Cash Dividend",
    assetTicker: "NYSE:LMT",
    quantity: 1,
    price: 3.15,
    fees: 0,
    currency: "AUD",
    platform: "CDIA - Dividends",
    assetClass: "Stock",
    sector: "Others",
    country: "Australia",
    strategy: "Dividend",
    notes: null
  },
  {
    id: "txn_000305",
    source: "initial_excel_import",
    sourceRow: 297,
    date: "2025-01-01",
    action: "Cash Interest",
    assetTicker: "Interest",
    quantity: 1,
    price: 0.01,
    fees: 0,
    currency: "AUD",
    platform: "CDIA - Dividends",
    assetClass: "Cash",
    sector: "Others",
    country: "Australia",
    strategy: "Dividend",
    notes: null
  },
  {
    id: "txn_000306",
    source: "initial_excel_import",
    sourceRow: 298,
    date: "2025-01-14",
    action: "Cash Deposit",
    assetTicker: "Cash",
    quantity: 1,
    price: 150,
    fees: 0,
    currency: "AUD",
    platform: "Commsec Bank",
    assetClass: "Cash",
    notes: "Kieren Chan"
  },
  {
    id: "txn_000307",
    source: "initial_excel_import",
    sourceRow: 299,
    date: "2025-01-16",
    action: "Cash Deposit",
    assetTicker: "Cash",
    quantity: 1,
    price: 150,
    fees: 0,
    currency: "AUD",
    platform: "Commsec Bank",
    assetClass: "Cash",
    notes: "Sam Thomas"
  },
  {
    id: "txn_000308",
    source: "initial_excel_import",
    sourceRow: 300,
    date: "2025-01-16",
    action: "Cash Dividend",
    assetTicker: "ASX:SEMI",
    quantity: 1,
    price: 2.37,
    fees: 0,
    currency: "AUD",
    platform: "CDIA - Dividends",
    assetClass: "Stock",
    sector: "Others",
    country: "Australia",
    strategy: "Dividend",
    notes: null
  },
  {
    id: "txn_000309",
    source: "initial_excel_import",
    sourceRow: 301,
    date: "2025-01-17",
    action: "Cash Dividend",
    assetTicker: "VAS.AX",
    quantity: 1,
    price: 6.78,
    fees: 0,
    currency: "AUD",
    platform: "CDIA - Dividends",
    assetClass: "Stock",
    sector: "ETF",
    country: "Australia",
    strategy: "Dividend",
    notes: null
  },
  {
    id: "txn_000310",
    source: "initial_excel_import",
    sourceRow: 302,
    date: "2025-01-18",
    action: "Cash Deposit",
    assetTicker: "Cash",
    quantity: 1,
    price: 300,
    fees: 0,
    currency: "AUD",
    platform: "Commsec Bank",
    assetClass: "Cash",
    notes: "Marc Mario"
  },
  {
    id: "txn_000311",
    source: "initial_excel_import",
    sourceRow: 303,
    date: "2025-01-20",
    action: "Cash Deposit",
    assetTicker: "Cash",
    quantity: 1,
    price: 150,
    fees: 0,
    currency: "AUD",
    platform: "Commsec Bank",
    assetClass: "Cash",
    notes: "Tom Flitcroft"
  },
  {
    id: "txn_000312",
    source: "initial_excel_import",
    sourceRow: 304,
    date: "2025-01-27",
    action: "Cash Withdrawal",
    assetTicker: "Cash",
    quantity: 1,
    price: 189,
    fees: 0,
    currency: "AUD",
    platform: "Commsec Bank",
    assetClass: "Cash",
    notes: "Business Renewal "
  },
  {
    id: "txn_000313",
    source: "initial_excel_import",
    sourceRow: 305,
    date: "2025-02-01",
    action: "Cash Interest",
    assetTicker: "Interest",
    quantity: 1,
    price: 0.02,
    fees: 0,
    currency: "AUD",
    platform: "CDIA - Dividends",
    assetClass: "Cash",
    sector: "Others",
    country: "Australia",
    strategy: "Dividend",
    notes: null
  }
];
