import type { SeedTransaction } from "../types";

export const transactions022: SeedTransaction[] = [
  {
    id: "txn_000214",
    source: "initial_excel_import",
    sourceRow: 216,
    date: "2024-07-12",
    action: "Cash Deposit",
    assetTicker: "Cash",
    quantity: 1,
    price: 125.00,
    fees: 0,
    currency: "AUD",
    platform: "Commsec Bank",
    assetClass: "Cash",
    notes: "Kieren Chan"
  },
  {
    id: "txn_000215",
    source: "initial_excel_import",
    sourceRow: 217,
    date: "2024-07-15",
    action: "Cash Dividend",
    assetTicker: "ASX:SEMI",
    quantity: 1,
    price: 2.73,
    fees: 0,
    currency: "AUD",
    platform: "CDIA - Dividends",
    assetClass: "Stock",
    sector: "Technology",
    country: "Australia",
    strategy: "Dividend",
    notes: null
  },
  {
    id: "txn_000216",
    source: "initial_excel_import",
    sourceRow: 218,
    date: "2024-07-18",
    action: "Cash Deposit",
    assetTicker: "Cash",
    quantity: 1,
    price: 125.00,
    fees: 0,
    currency: "AUD",
    platform: "Commsec Bank",
    assetClass: "Cash",
    notes: "Sam Thomas"
  },
  {
    id: "txn_000217",
    source: "initial_excel_import",
    sourceRow: 219,
    date: "2024-07-19",
    action: "Cash Deposit",
    assetTicker: "Cash",
    quantity: 1,
    price: 125.00,
    fees: 0,
    currency: "AUD",
    platform: "Commsec Bank",
    assetClass: "Cash",
    notes: "Tom Flitcroft"
  },
  {
    id: "txn_000218",
    source: "initial_excel_import",
    sourceRow: 220,
    date: "2024-08-01",
    action: "Cash Interest",
    assetTicker: "Interest",
    quantity: 1,
    price: 0.67,
    fees: 0,
    currency: "AUD",
    platform: "CDIA - Dividends",
    assetClass: "Cash",
    sector: "Others",
    country: "Australia",
    strategy: "Dividend",
    notes: null
  },
  {
    id: "txn_000219",
    source: "initial_excel_import",
    sourceRow: 221,
    date: "2024-08-14",
    action: "Cash Deposit",
    assetTicker: "Cash",
    quantity: 1,
    price: 125.00,
    fees: 0,
    currency: "AUD",
    platform: "Commsec Bank",
    assetClass: "Cash",
    notes: "Kieren Chan"
  },
  {
    id: "txn_000220",
    source: "initial_excel_import",
    sourceRow: 222,
    date: "2024-08-16",
    action: "Cash Deposit",
    assetTicker: "Cash",
    quantity: 1,
    price: 125.00,
    fees: 0,
    currency: "AUD",
    platform: "Commsec Bank",
    assetClass: "Cash",
    notes: "Sam Thomas"
  },
  {
    id: "txn_000221",
    source: "initial_excel_import",
    sourceRow: 223,
    date: "2024-08-19",
    action: "Cash Deposit",
    assetTicker: "Cash",
    quantity: 1,
    price: 125.00,
    fees: 0,
    currency: "AUD",
    platform: "Commsec Bank",
    assetClass: "Cash",
    notes: "Tom Flitcroft"
  },
  {
    id: "txn_000222",
    source: "initial_excel_import",
    sourceRow: 224,
    date: "2024-08-26",
    action: "Cash Dividend",
    assetTicker: "ASX:GMG",
    quantity: 1,
    price: 8.14,
    fees: 0,
    currency: "AUD",
    platform: "CDIA - Dividends",
    assetClass: "Stock",
    sector: "Real Estate",
    country: "Australia",
    strategy: "Dividend",
    notes: null
  },
  {
    id: "txn_000223",
    source: "initial_excel_import",
    sourceRow: 225,
    date: "2024-08-30",
    action: "Cash Dividend",
    assetTicker: "ASX:NAB",
    quantity: 1,
    price: 41.58,
    fees: 0,
    currency: "AUD",
    platform: "CDIA - Dividends",
    assetClass: "Stock",
    sector: "Financials",
    country: "Australia",
    strategy: "Dividend",
    notes: null
  }
];
