import type { SeedTransaction } from "../types";

export const transactions007: SeedTransaction[] = [
  {
    id: "txn_000064",
    source: "initial_excel_import",
    sourceRow: 66,
    date: "2022-03-30",
    action: "Cash Dividend",
    assetTicker: "ASX:FMG",
    quantity: 1,
    price: 49.88,
    fees: 0,
    currency: "AUD",
    platform: "CDIA - Dividends",
    assetClass: "Stock",
    sector: "Materials",
    country: "Australia",
    strategy: "Dividend",
    notes: null
  },
  {
    id: "txn_000065",
    source: "initial_excel_import",
    sourceRow: 67,
    date: "2022-04-14",
    action: "Cash Deposit",
    assetTicker: "Cash",
    quantity: 1,
    price: 125,
    fees: 0,
    currency: "AUD",
    platform: "Commsec Bank",
    assetClass: "Cash",
    notes: "Kieren Chan"
  },
  {
    id: "txn_000066",
    source: "initial_excel_import",
    sourceRow: 68,
    date: "2022-04-18",
    action: "Cash Deposit",
    assetTicker: "Cash",
    quantity: 1,
    price: 125,
    fees: 0,
    currency: "AUD",
    platform: "Commsec Bank",
    assetClass: "Cash",
    notes: "Sam Thomas"
  },
  {
    id: "txn_000067",
    source: "initial_excel_import",
    sourceRow: 69,
    date: "2022-04-20",
    action: "Cash Deposit",
    assetTicker: "Cash",
    quantity: 1,
    price: 125,
    fees: 0,
    currency: "AUD",
    platform: "Commsec Bank",
    assetClass: "Cash",
    notes: "Tom Flitcroft"
  },
  {
    id: "txn_000068",
    source: "initial_excel_import",
    sourceRow: 70,
    date: "2022-04-21",
    action: "Cash Deposit",
    assetTicker: "Cash",
    quantity: 1,
    price: 125,
    fees: 0,
    currency: "AUD",
    platform: "Commsec Bank",
    assetClass: "Cash",
    notes: "Marc Mario"
  },
  {
    id: "txn_000069",
    source: "initial_excel_import",
    sourceRow: 71,
    date: "2022-04-28",
    action: "Cash Withdrawal",
    assetTicker: "Cash",
    quantity: 1,
    price: 500,
    fees: 0,
    currency: "AUD",
    platform: "Commsec Bank",
    assetClass: "Cash",
    notes: "Coin Spot"
  },
  {
    id: "txn_000070",
    source: "initial_excel_import",
    sourceRow: 72,
    date: "2022-04-28",
    action: "Transfer Send",
    assetTicker: "Cash",
    quantity: 1,
    price: 500,
    fees: 0,
    currency: "AUD",
    platform: "Commsec Shares",
    assetClass: "Cash",
    notes: null
  },
  {
    id: "txn_000071",
    source: "initial_excel_import",
    sourceRow: 73,
    date: "2022-04-28",
    action: "Buy",
    assetTicker: "ASX:SEMI",
    quantity: 57,
    price: 8.85,
    fees: 10,
    currency: "AUD",
    platform: "Commsec Shares",
    assetClass: "Stock",
    sector: "Others",
    country: "Australia",
    strategy: "Medium Risk",
    notes: null
  },
  {
    id: "txn_000072",
    source: "initial_excel_import",
    sourceRow: 74,
    date: "2022-05-02",
    action: "Buy",
    assetTicker: "ETH-AUD",
    quantity: 0.12136923,
    price: 4078.87159662,
    fees: 4.95,
    currency: "AUD",
    platform: "Coinbase",
    assetClass: "Crypto",
    sector: "Crypto",
    country: "Crypto World",
    strategy: "High Risk",
    notes: null
  },
  {
    id: "txn_000073",
    source: "initial_excel_import",
    sourceRow: 75,
    date: "2022-05-12",
    action: "Cash Deposit",
    assetTicker: "Cash",
    quantity: 1,
    price: 125,
    fees: 0,
    currency: "AUD",
    platform: "Commsec Bank",
    assetClass: "Cash",
    notes: "Kieren Chan"
  }
];
