import type { SeedTransaction } from "../types";

export const transactions011: SeedTransaction[] = [
  {
    id: "txn_000104",
    source: "initial_excel_import",
    sourceRow: 106,
    date: "2022-11-18",
    action: "Cash Deposit",
    assetTicker: "Cash",
    quantity: 1,
    price: 125,
    fees: 0,
    currency: "AUD",
    platform: "Commsec Bank",
    assetClass: "Cash",
    notes: "Sam Thomas"
  },
  {
    id: "txn_000105",
    source: "initial_excel_import",
    sourceRow: 107,
    date: "2022-11-21",
    action: "Cash Deposit",
    assetTicker: "Cash",
    quantity: 1,
    price: 125,
    fees: 0,
    currency: "AUD",
    platform: "Commsec Bank",
    assetClass: "Cash",
    notes: "Tom Flitcroft"
  },
  {
    id: "txn_000106",
    source: "initial_excel_import",
    sourceRow: 108,
    date: "2022-11-24",
    action: "Buy",
    assetTicker: "ETH-AUD",
    quantity: 0.27714341,
    price: 1786.25753703,
    fees: 4.95,
    currency: "AUD",
    platform: "Coinbase",
    assetClass: "Crypto",
    sector: "Crypto",
    country: "Crypto World",
    strategy: "High Risk",
    notes: null
  },
  {
    id: "txn_000107",
    source: "initial_excel_import",
    sourceRow: 109,
    date: "2022-12-14",
    action: "Cash Deposit",
    assetTicker: "Cash",
    quantity: 1,
    price: 125,
    fees: 0,
    currency: "AUD",
    platform: "Commsec Bank",
    assetClass: "Cash",
    notes: "Kieren Chan"
  },
  {
    id: "txn_000108",
    source: "initial_excel_import",
    sourceRow: 110,
    date: "2022-12-16",
    action: "Cash Deposit",
    assetTicker: "Cash",
    quantity: 1,
    price: 375,
    fees: 0,
    currency: "AUD",
    platform: "Commsec Bank",
    assetClass: "Cash",
    notes: "Marc Mario"
  },
  {
    id: "txn_000109",
    source: "initial_excel_import",
    sourceRow: 111,
    date: "2023-01-12",
    action: "Cash Deposit",
    assetTicker: "Cash",
    quantity: 1,
    price: 125,
    fees: 0,
    currency: "AUD",
    platform: "Commsec Bank",
    assetClass: "Cash",
    notes: "Kieren Chan"
  },
  {
    id: "txn_000110",
    source: "initial_excel_import",
    sourceRow: 112,
    date: "2023-01-17",
    action: "Cash Dividend",
    assetTicker: "ASX:SEMI",
    quantity: 1,
    price: 2.29,
    fees: 0,
    currency: "AUD",
    platform: "CDIA - Dividends",
    assetClass: "Stock",
    sector: "Others",
    country: "Australia",
    strategy: "Dividend",
    notes: null
  },
  {
    id: "txn_000111",
    source: "initial_excel_import",
    sourceRow: 113,
    date: "2023-01-18",
    action: "Cash Deposit",
    assetTicker: "Cash",
    quantity: 1,
    price: 125,
    fees: 0,
    currency: "AUD",
    platform: "Commsec Bank",
    assetClass: "Cash",
    notes: "Sam Thomas"
  },
  {
    id: "txn_000112",
    source: "initial_excel_import",
    sourceRow: 114,
    date: "2023-01-18",
    action: "Cash Deposit",
    assetTicker: "Cash",
    quantity: 1,
    price: 250,
    fees: 0,
    currency: "AUD",
    platform: "Commsec Bank",
    assetClass: "Cash",
    notes: "Tom Flitcroft"
  },
  {
    id: "txn_000113",
    source: "initial_excel_import",
    sourceRow: 115,
    date: "2023-01-28",
    action: "Cash Deposit",
    assetTicker: "Cash",
    quantity: 1,
    price: 125,
    fees: 0,
    currency: "AUD",
    platform: "Commsec Bank",
    assetClass: "Cash",
    notes: "Marc Mario"
  }
];
