import type { SeedTransaction } from "../types";

export const transactions032: SeedTransaction[] = [
  {
    id: "txn_000314",
    source: "initial_excel_import",
    sourceRow: 306,
    date: "2025-02-11",
    action: "Cash Deposit",
    assetTicker: "Cash",
    quantity: 1,
    price: 150.00,
    fees: 0,
    currency: "AUD",
    platform: "Commsec Bank",
    assetClass: "Cash",
    notes: "Kieren Chan"
  },
  {
    id: "txn_000315",
    source: "initial_excel_import",
    sourceRow: 307,
    date: "2025-02-17",
    action: "Cash Deposit",
    assetTicker: "Cash",
    quantity: 1,
    price: 150.00,
    fees: 0,
    currency: "AUD",
    platform: "Commsec Bank",
    assetClass: "Cash",
    notes: "Sam Thomas"
  },
  {
    id: "txn_000316",
    source: "initial_excel_import",
    sourceRow: 308,
    date: "2025-02-18",
    action: "Cash Deposit",
    assetTicker: "Cash",
    quantity: 1,
    price: 150.00,
    fees: 0,
    currency: "AUD",
    platform: "Commsec Bank",
    assetClass: "Cash",
    notes: "Tom Flitcroft"
  },
  {
    id: "txn_000317",
    source: "initial_excel_import",
    sourceRow: 309,
    date: "2025-02-25",
    action: "Cash Dividend",
    assetTicker: "ASX:GMG",
    quantity: 1,
    price: 5.10,
    fees: 0,
    currency: "AUD",
    platform: "CDIA - Dividends",
    assetClass: "Stock",
    sector: "Real Estate",
    country: "Australia",
    strategy: "Dividend",
    notes: null
  },
  {
    id: "txn_000318",
    source: "initial_excel_import",
    sourceRow: 310,
    date: "2025-03-01",
    action: "Cash Interest",
    assetTicker: "Interest",
    quantity: 1,
    price: 0.01,
    fees: 0,
    currency: "AUD",
    platform: "CDIA - Dividends",
    assetClass: "Cash",
    sector: "Others",
    country: "Australia",
    strategy: "Dividend",
    notes: null
  },
  {
    id: "txn_000319",
    source: "initial_excel_import",
    sourceRow: 311,
    date: "2025-03-13",
    action: "Cash Deposit",
    assetTicker: "Cash",
    quantity: 1,
    price: 150.00,
    fees: 0,
    currency: "AUD",
    platform: "Commsec Bank",
    assetClass: "Cash",
    notes: "Kieren Chan"
  },
  {
    id: "txn_000320",
    source: "initial_excel_import",
    sourceRow: 312,
    date: "2025-03-17",
    action: "Cash Deposit",
    assetTicker: "Cash",
    quantity: 1,
    price: 150.00,
    fees: 0,
    currency: "AUD",
    platform: "Commsec Bank",
    assetClass: "Cash",
    notes: "Sam Thomas"
  },
  {
    id: "txn_000321",
    source: "initial_excel_import",
    sourceRow: 313,
    date: "2025-03-18",
    action: "Cash Deposit",
    assetTicker: "Cash",
    quantity: 1,
    price: 150.00,
    fees: 0,
    currency: "AUD",
    platform: "Commsec Bank",
    assetClass: "Cash",
    notes: "Tom Flitcroft"
  },
  {
    id: "txn_000322",
    source: "initial_excel_import",
    sourceRow: 314,
    date: "2025-03-19",
    action: "Cash Dividend",
    assetTicker: "ASX:AIZ",
    quantity: 1,
    price: 13.49,
    fees: 0,
    currency: "AUD",
    platform: "CDIA - Dividends",
    assetClass: "Stock",
    sector: "Others",
    country: "Australia",
    strategy: "Dividend",
    notes: null
  },
  {
    id: "txn_000323",
    source: "initial_excel_import",
    sourceRow: 315,
    date: "2025-03-23",
    action: "Cash Deposit",
    assetTicker: "Cash",
    quantity: 1,
    price: 150.00,
    fees: 0,
    currency: "AUD",
    platform: "Commsec Bank",
    assetClass: "Cash",
    notes: "Marc Mario"
  }
];
