import type { SeedTransaction } from "../types";

export const transactions037: SeedTransaction[] = [
  {
    id: "txn_000364",
    source: "initial_excel_import",
    sourceRow: 356,
    date: "2025-07-28",
    action: "Cash Withdrawal",
    assetTicker: "Cash",
    quantity: 1,
    price: 2.09,
    fees: 0,
    currency: "AUD",
    platform: "Commsec Bank",
    assetClass: "Cash",
    notes: null
  },
  {
    id: "txn_000365",
    source: "initial_excel_import",
    sourceRow: 357,
    date: "2025-08-01",
    action: "Sell",
    assetTicker: "ASX:RFG",
    quantity: 419,
    price: 1.885,
    fees: 4.99,
    currency: "AUD",
    platform: "Commsec Shares",
    assetClass: "Stock",
    sector: "Real Estate",
    country: "Australia",
    strategy: "High Risk",
    notes: "Agreed - 31 July 2025 Meeting"
  },
  {
    id: "txn_000366",
    source: "initial_excel_import",
    sourceRow: 358,
    date: "2025-08-01",
    action: "Buy",
    assetTicker: "ASX:EDV",
    quantity: 120,
    price: 4.04,
    fees: 4.99,
    currency: "AUD",
    platform: "Commsec Shares",
    assetClass: "Stock",
    sector: "Consumer Staples",
    country: "Australia",
    strategy: "Dividend",
    notes: "Agreed - 31 July 2025 Meeting"
  },
  {
    id: "txn_000367",
    source: "initial_excel_import",
    sourceRow: 359,
    date: "2025-08-01",
    action: "Buy",
    assetTicker: "VAS.AX",
    quantity: 14,
    price: 107.15,
    fees: 10,
    currency: "AUD",
    platform: "Commsec Shares",
    assetClass: "ETF",
    sector: "ETF",
    country: "Australia",
    strategy: "Dividend",
    notes: "Agreed - 31 July 2025 Meeting"
  },
  {
    id: "txn_000368",
    source: "initial_excel_import",
    sourceRow: 360,
    date: "2025-08-01",
    action: "Cash Withdrawal",
    assetTicker: "Cash",
    quantity: 1,
    price: 1200,
    fees: 0,
    currency: "AUD",
    platform: "Commsec Bank",
    assetClass: "Cash",
    notes: null
  },
  {
    id: "txn_000369",
    source: "initial_excel_import",
    sourceRow: 361,
    date: "2025-08-01",
    action: "Cash Deposit",
    assetTicker: "Cash",
    quantity: 1,
    price: 1200,
    fees: 0,
    currency: "AUD",
    platform: "Commsec Bank",
    assetClass: "Cash",
    notes: null
  },
  {
    id: "txn_000370",
    source: "initial_excel_import",
    sourceRow: 362,
    date: "2025-08-01",
    action: "Cash Interest",
    assetTicker: "Interest",
    quantity: 1,
    price: 0.01,
    fees: 0,
    currency: "AUD",
    platform: "CDIA - Dividends",
    assetClass: "Cash",
    sector: "Others",
    country: "Australia",
    strategy: "Dividend",
    notes: null
  },
  {
    id: "txn_000371",
    source: "initial_excel_import",
    sourceRow: 363,
    date: "2025-08-14",
    action: "Buy",
    assetTicker: "NYSE:ALB",
    quantity: 6.2377,
    price: 81.2788,
    fees: 5,
    currency: "USD",
    platform: "Commsec International Shares",
    assetClass: "Stock",
    sector: "Materials",
    country: "United States",
    strategy: "High Risk",
    notes: "Kieren Selected"
  },
  {
    id: "txn_000372",
    source: "initial_excel_import",
    sourceRow: 364,
    date: "2025-08-14",
    action: "Sell",
    assetTicker: "BNB-AUD",
    quantity: 0.25475805,
    price: 1314.31,
    fees: 3.35,
    currency: "AUD",
    platform: "Coinbase",
    assetClass: "Crypto",
    sector: "Crypto",
    country: "Crypto World",
    strategy: "High Risk",
    notes: null
  },
  {
    id: "txn_000373",
    source: "initial_excel_import",
    sourceRow: 365,
    date: "2025-08-14",
    action: "Sell",
    assetTicker: "ETH-AUD",
    quantity: 0.3484442,
    price: 7247.22,
    fees: 25.25,
    currency: "AUD",
    platform: "Coinbase",
    assetClass: "Crypto",
    sector: "Crypto",
    country: "Crypto World",
    strategy: "High Risk",
    notes: null
  }
];
