import type { SeedTransaction } from "../types";

export const transactions027: SeedTransaction[] = [
  {
    id: "txn_000264",
    source: "initial_excel_import",
    sourceRow: 256,
    date: "2024-08-16",
    action: "Cash Deposit",
    assetTicker: "Cash",
    quantity: 1,
    price: 125.00,
    fees: 0,
    currency: "AUD",
    platform: "Commsec Bank",
    assetClass: "Cash",
    notes: "Sam Thomas"
  },
  {
    id: "txn_000265",
    source: "initial_excel_import",
    sourceRow: 257,
    date: "2024-08-26",
    action: "Cash Dividend",
    assetTicker: "ASX:GMG",
    quantity: 1,
    price: 6.10,
    fees: 0,
    currency: "AUD",
    platform: "CDIA - Dividends",
    assetClass: "Stock",
    sector: "Real Estate",
    country: "Australia",
    strategy: "Dividend",
    notes: null
  },
  {
    id: "txn_000266",
    source: "initial_excel_import",
    sourceRow: 258,
    date: "2024-08-28",
    action: "Cash Deposit",
    assetTicker: "Cash",
    quantity: 1,
    price: 125.00,
    fees: 0,
    currency: "AUD",
    platform: "Commsec Bank",
    assetClass: "Cash",
    notes: "Kieren Chan"
  },
  {
    id: "txn_000267",
    source: "initial_excel_import",
    sourceRow: 259,
    date: "2024-09-01",
    action: "Cash Interest",
    assetTicker: "Interest",
    quantity: 1,
    price: 0.06,
    fees: 0,
    currency: "AUD",
    platform: "CDIA - Dividends",
    assetClass: "Cash",
    sector: "Others",
    country: "Australia",
    strategy: "Dividend",
    notes: null
  },
  {
    id: "txn_000268",
    source: "initial_excel_import",
    sourceRow: 260,
    date: "2024-09-01",
    action: "Cash Interest",
    assetTicker: "Interest",
    quantity: 1,
    price: 0.06,
    fees: 0,
    currency: "AUD",
    platform: "CDIA - Dividends",
    assetClass: "Cash",
    sector: "Others",
    country: "Australia",
    strategy: "Dividend",
    notes: null
  },
  {
    id: "txn_000269",
    source: "initial_excel_import",
    sourceRow: 261,
    date: "2024-09-08",
    action: "Cash Withdrawal",
    assetTicker: "Cash",
    quantity: 1,
    price: 1000.00,
    fees: 0,
    currency: "AUD",
    platform: "Commsec Bank",
    assetClass: "Cash",
    notes: "Coin Spot"
  },
  {
    id: "txn_000270",
    source: "initial_excel_import",
    sourceRow: 262,
    date: "2024-09-09",
    action: "Buy",
    assetTicker: "ETH-AUD",
    quantity: 0.13965115,
    price: 3544.90102624,
    fees: 4.95,
    currency: "AUD",
    platform: "Coinbase",
    assetClass: "Crypto",
    sector: "Crypto",
    country: "Crypto World",
    strategy: "High Risk",
    notes: null
  },
  {
    id: "txn_000271",
    source: "initial_excel_import",
    sourceRow: 263,
    date: "2024-09-09",
    action: "Buy",
    assetTicker: "SOL-AUD",
    quantity: 2.49214972,
    price: 198.64356502,
    fees: 4.95,
    currency: "AUD",
    platform: "Coinbase",
    assetClass: "Crypto",
    sector: "Crypto",
    country: "Crypto World",
    strategy: "High Risk",
    notes: null
  },
  {
    id: "txn_000272",
    source: "initial_excel_import",
    sourceRow: 264,
    date: "2024-09-16",
    action: "Cash Deposit",
    assetTicker: "Cash",
    quantity: 1,
    price: 125.00,
    fees: 0,
    currency: "AUD",
    platform: "Commsec Bank",
    assetClass: "Cash",
    notes: "Sam Thomas"
  },
  {
    id: "txn_000273",
    source: "initial_excel_import",
    sourceRow: 265,
    date: "2024-09-18",
    action: "Cash Deposit",
    assetTicker: "Cash",
    quantity: 1,
    price: 125.00,
    fees: 0,
    currency: "AUD",
    platform: "Commsec Bank",
    assetClass: "Cash",
    notes: "Tom Flitcroft"
  }
];
