import type { SeedTransaction } from "../types";

export const transactions016: SeedTransaction[] = [
  {
    id: "txn_000154",
    source: "initial_excel_import",
    sourceRow: 156,
    date: "2023-08-01",
    action: "Cash Interest",
    assetTicker: "Interest",
    quantity: 1,
    price: 0.05,
    fees: 0,
    currency: "AUD",
    platform: "CDIA - Dividends",
    assetClass: "Cash",
    sector: "Others",
    country: "Australia",
    strategy: "Dividend",
    notes: null
  },
  {
    id: "txn_000155",
    source: "initial_excel_import",
    sourceRow: 157,
    date: "2023-08-15",
    action: "Cash Deposit",
    assetTicker: "Cash",
    quantity: 1,
    price: 125,
    fees: 0,
    currency: "AUD",
    platform: "Commsec Bank",
    assetClass: "Cash",
    notes: "Kieren Chan"
  },
  {
    id: "txn_000156",
    source: "initial_excel_import",
    sourceRow: 158,
    date: "2023-08-18",
    action: "Buy",
    assetTicker: "ETH-AUD",
    quantity: 0.36873972,
    price: 2685.08911896,
    fees: 9.90,
    currency: "AUD",
    platform: "Coinbase",
    assetClass: "Crypto",
    sector: "Crypto",
    country: "Crypto World",
    strategy: "High Risk",
    notes: null
  },
  {
    id: "txn_000157",
    source: "initial_excel_import",
    sourceRow: 159,
    date: "2023-08-18",
    action: "Cash Deposit",
    assetTicker: "Cash",
    quantity: 1,
    price: 125,
    fees: 0,
    currency: "AUD",
    platform: "Commsec Bank",
    assetClass: "Cash",
    notes: "Sam Thomas"
  },
  {
    id: "txn_000158",
    source: "initial_excel_import",
    sourceRow: 160,
    date: "2023-08-18",
    action: "Cash Deposit",
    assetTicker: "Cash",
    quantity: 1,
    price: 125,
    fees: 0,
    currency: "AUD",
    platform: "Commsec Bank",
    assetClass: "Cash",
    notes: "Tom Flitcroft"
  },
  {
    id: "txn_000159",
    source: "initial_excel_import",
    sourceRow: 161,
    date: "2023-08-25",
    action: "Cash Dividend",
    assetTicker: "ASX:GMG",
    quantity: 1,
    price: 6.10,
    fees: 0,
    currency: "AUD",
    platform: "CDIA - Dividends",
    assetClass: "Stock",
    sector: "Real Estate",
    country: "Australia",
    strategy: "Dividend",
    notes: null
  },
  {
    id: "txn_000160",
    source: "initial_excel_import",
    sourceRow: 162,
    date: "2023-09-17",
    action: "Cash Deposit",
    assetTicker: "Cash",
    quantity: 1,
    price: 125,
    fees: 0,
    currency: "AUD",
    platform: "Commsec Bank",
    assetClass: "Cash",
    notes: "Sam Thomas"
  },
  {
    id: "txn_000161",
    source: "initial_excel_import",
    sourceRow: 163,
    date: "2023-09-18",
    action: "Cash Deposit",
    assetTicker: "Cash",
    quantity: 1,
    price: 125,
    fees: 0,
    currency: "AUD",
    platform: "Commsec Bank",
    assetClass: "Cash",
    notes: "Tom Flitcroft"
  },
  {
    id: "txn_000162",
    source: "initial_excel_import",
    sourceRow: 164,
    date: "2023-09-21",
    action: "Cash Dividend",
    assetTicker: "ASX:AIZ",
    quantity: 1,
    price: 76.98,
    fees: 0,
    currency: "AUD",
    platform: "CDIA - Dividends",
    assetClass: "Stock",
    sector: "Others",
    country: "Australia",
    strategy: "Dividend",
    notes: null
  },
  {
    id: "txn_000163",
    source: "initial_excel_import",
    sourceRow: 165,
    date: "2023-09-24",
    action: "Cash Deposit",
    assetTicker: "Cash",
    quantity: 1,
    price: 125,
    fees: 0,
    currency: "AUD",
    platform: "Commsec Bank",
    assetClass: "Cash",
    notes: "Kieren Chan"
  }
];
