import type { SeedTransaction } from "../types";

export const transactions044: SeedTransaction[] = [
  {
    id: "txn_000434",
    source: "initial_excel_import",
    sourceRow: 426,
    date: "2026-02-18",
    action: "Cash Deposit",
    assetTicker: "Cash",
    quantity: 1,
    price: 175.00,
    fees: 0,
    currency: "AUD",
    platform: "Commsec Bank",
    assetClass: "Cash",
    notes: "Tom Flitcroft"
  },
  {
    id: "txn_000435",
    source: "initial_excel_import",
    sourceRow: 427,
    date: "2026-02-25",
    action: "Cash Dividend",
    assetTicker: "ASX:GMG",
    quantity: 1,
    price: 6.82,
    fees: 0,
    currency: "AUD",
    platform: "CDIA - Dividends",
    assetClass: "Stock",
    sector: "Real Estate",
    country: "Australia",
    strategy: "Dividend",
    notes: null
  },
  {
    id: "txn_000436",
    source: "initial_excel_import",
    sourceRow: 428,
    date: "2026-03-01",
    action: "Cash Interest",
    assetTicker: "Interest",
    quantity: 1,
    price: 0.05,
    fees: 0,
    currency: "AUD",
    platform: "Commsec Bank",
    assetClass: "Cash",
    sector: "Others",
    country: "Australia",
    strategy: "Dividend",
    notes: null
  },
  {
    id: "txn_000437",
    source: "initial_excel_import",
    sourceRow: 429,
    date: "2026-03-13",
    action: "Cash Deposit",
    assetTicker: "Cash",
    quantity: 1,
    price: 175.00,
    fees: 0,
    currency: "AUD",
    platform: "Commsec Bank",
    assetClass: "Cash",
    notes: "Kieren Chan"
  },
  {
    id: "txn_000438",
    source: "initial_excel_import",
    sourceRow: 430,
    date: "2026-03-16",
    action: "Cash Deposit",
    assetTicker: "Cash",
    quantity: 1,
    price: 175.00,
    fees: 0,
    currency: "AUD",
    platform: "Commsec Bank",
    assetClass: "Cash",
    notes: "Sam Thomas"
  },
  {
    id: "txn_000439",
    source: "initial_excel_import",
    sourceRow: 431,
    date: "2026-03-17",
    action: "Cash Deposit",
    assetTicker: "Cash",
    quantity: 1,
    price: 175.00,
    fees: 0,
    currency: "AUD",
    platform: "Commsec Bank",
    assetClass: "Cash",
    notes: "Tom Flitcroft"
  },
  {
    id: "txn_000440",
    source: "initial_excel_import",
    sourceRow: 432,
    date: "2026-03-20",
    action: "Cash Dividend",
    assetTicker: "ASX:EDV",
    quantity: 1,
    price: 25.18,
    fees: 0,
    currency: "AUD",
    platform: "CDIA - Dividends",
    assetClass: "Stock",
    sector: "Consumer Staples",
    country: "Australia",
    strategy: "Dividend",
    notes: null
  },
  {
    id: "txn_000441",
    source: "initial_excel_import",
    sourceRow: 433,
    date: "2026-03-27",
    action: "Cash Dividend",
    assetTicker: "ASX:FMG",
    quantity: 1,
    price: 84.21,
    fees: 0,
    currency: "AUD",
    platform: "CDIA - Dividends",
    assetClass: "Stock",
    sector: "Materials",
    country: "Australia",
    strategy: "Dividend",
    notes: null
  },
  {
    id: "txn_000442",
    source: "initial_excel_import",
    sourceRow: 434,
    date: "2026-03-31",
    action: "Cash Interest",
    assetTicker: "Interest",
    quantity: 1,
    price: 0.05,
    fees: 0,
    currency: "AUD",
    platform: "Commsec Bank",
    assetClass: "Cash",
    sector: "Others",
    country: "Australia",
    strategy: "Dividend",
    notes: null
  },
  {
    id: "txn_000443",
    source: "initial_excel_import",
    sourceRow: 435,
    date: "2026-03-31",
    action: "Portfolio Snapshot",
    assetTicker: "Portfolio",
    quantity: 1,
    price: 0,
    fees: 0,
    currency: "AUD",
    platform: "TradeHub",
    assetClass: "System",
    notes: "Imported history checkpoint"
  }
];
