import type { SeedTransaction } from "../types";

export const transactions020: SeedTransaction[] = [
  {
    id: "txn_000194",
    source: "initial_excel_import",
    sourceRow: 196,
    date: "2024-04-12",
    action: "Cash Deposit",
    assetTicker: "Cash",
    quantity: 1,
    price: 125.00,
    fees: 0,
    currency: "AUD",
    platform: "Commsec Bank",
    assetClass: "Cash",
    notes: "Kieren Chan"
  },
  {
    id: "txn_000195",
    source: "initial_excel_import",
    sourceRow: 197,
    date: "2024-04-18",
    action: "Cash Deposit",
    assetTicker: "Cash",
    quantity: 1,
    price: 125.00,
    fees: 0,
    currency: "AUD",
    platform: "Commsec Bank",
    assetClass: "Cash",
    notes: "Sam Thomas"
  },
  {
    id: "txn_000196",
    source: "initial_excel_import",
    sourceRow: 198,
    date: "2024-04-19",
    action: "Cash Deposit",
    assetTicker: "Cash",
    quantity: 1,
    price: 125.00,
    fees: 0,
    currency: "AUD",
    platform: "Commsec Bank",
    assetClass: "Cash",
    notes: "Tom Flitcroft"
  },
  {
    id: "txn_000197",
    source: "initial_excel_import",
    sourceRow: 199,
    date: "2024-04-23",
    action: "Cash Withdrawal",
    assetTicker: "Cash",
    quantity: 1,
    price: 1000.00,
    fees: 0,
    currency: "AUD",
    platform: "Commsec Bank",
    assetClass: "Cash",
    notes: "CoinSpot Transfer"
  },
  {
    id: "txn_000198",
    source: "initial_excel_import",
    sourceRow: 200,
    date: "2024-04-23",
    action: "Buy",
    assetTicker: "ETH-AUD",
    quantity: 0.27489153,
    price: 3637.78,
    fees: 9.90,
    currency: "AUD",
    platform: "CoinSpot",
    assetClass: "Crypto",
    sector: "Crypto",
    country: "Crypto World",
    strategy: "High Risk",
    notes: null
  },
  {
    id: "txn_000199",
    source: "initial_excel_import",
    sourceRow: 201,
    date: "2024-05-01",
    action: "Cash Interest",
    assetTicker: "Interest",
    quantity: 1,
    price: 0.41,
    fees: 0,
    currency: "AUD",
    platform: "CDIA - Dividends",
    assetClass: "Cash",
    sector: "Others",
    country: "Australia",
    strategy: "Dividend",
    notes: null
  },
  {
    id: "txn_000200",
    source: "initial_excel_import",
    sourceRow: 202,
    date: "2024-05-14",
    action: "Cash Deposit",
    assetTicker: "Cash",
    quantity: 1,
    price: 125.00,
    fees: 0,
    currency: "AUD",
    platform: "Commsec Bank",
    assetClass: "Cash",
    notes: "Kieren Chan"
  },
  {
    id: "txn_000201",
    source: "initial_excel_import",
    sourceRow: 203,
    date: "2024-05-17",
    action: "Cash Deposit",
    assetTicker: "Cash",
    quantity: 1,
    price: 125.00,
    fees: 0,
    currency: "AUD",
    platform: "Commsec Bank",
    assetClass: "Cash",
    notes: "Sam Thomas"
  },
  {
    id: "txn_000202",
    source: "initial_excel_import",
    sourceRow: 204,
    date: "2024-05-20",
    action: "Cash Deposit",
    assetTicker: "Cash",
    quantity: 1,
    price: 125.00,
    fees: 0,
    currency: "AUD",
    platform: "Commsec Bank",
    assetClass: "Cash",
    notes: "Tom Flitcroft"
  },
  {
    id: "txn_000203",
    source: "initial_excel_import",
    sourceRow: 205,
    date: "2024-05-29",
    action: "Cash Dividend",
    assetTicker: "ASX:GMG",
    quantity: 1,
    price: 7.91,
    fees: 0,
    currency: "AUD",
    platform: "CDIA - Dividends",
    assetClass: "Stock",
    sector: "Real Estate",
    country: "Australia",
    strategy: "Dividend",
    notes: null
  }
];
