import type { SeedTransaction } from "../types";

export const transactions033: SeedTransaction[] = [
  {
    id: "txn_000324",
    source: "initial_excel_import",
    sourceRow: 316,
    date: "2025-03-27",
    action: "Cash Dividend",
    assetTicker: "ASX:FMG",
    quantity: 1,
    price: 66.50,
    fees: 0,
    currency: "AUD",
    platform: "CDIA - Dividends",
    assetClass: "Stock",
    sector: "Materials",
    country: "Australia",
    strategy: "Dividend",
    notes: null
  },
  {
    id: "txn_000325",
    source: "initial_excel_import",
    sourceRow: 317,
    date: "2025-04-01",
    action: "Cash Interest",
    assetTicker: "Interest",
    quantity: 1,
    price: 0.01,
    fees: 0,
    currency: "AUD",
    platform: "CDIA - Dividends",
    assetClass: "Cash",
    sector: "Others",
    country: "Australia",
    strategy: "Dividend",
    notes: null
  },
  {
    id: "txn_000326",
    source: "initial_excel_import",
    sourceRow: 318,
    date: "2025-04-02",
    action: "Cash Dividend",
    assetTicker: "ASX:WDS",
    quantity: 1,
    price: 29.70,
    fees: 0,
    currency: "AUD",
    platform: "CDIA - Dividends",
    assetClass: "Stock",
    sector: "Energy",
    country: "Australia",
    strategy: "Dividend",
    notes: null
  },
  {
    id: "txn_000327",
    source: "initial_excel_import",
    sourceRow: 319,
    date: "2025-04-08",
    action: "Cash Deposit",
    assetTicker: "Cash",
    quantity: 1,
    price: 150.00,
    fees: 0,
    currency: "AUD",
    platform: "Commsec Bank",
    assetClass: "Cash",
    notes: "Kieren Chan"
  },
  {
    id: "txn_000328",
    source: "initial_excel_import",
    sourceRow: 320,
    date: "2025-04-10",
    action: "Cash Dividend",
    assetTicker: "ASX:EDV",
    quantity: 1,
    price: 18.88,
    fees: 0,
    currency: "AUD",
    platform: "CDIA - Dividends",
    assetClass: "Stock",
    sector: "Consumer Staples",
    country: "Australia",
    strategy: "Dividend",
    notes: null
  },
  {
    id: "txn_000329",
    source: "initial_excel_import",
    sourceRow: 321,
    date: "2025-04-14",
    action: "Cash Dividend",
    assetTicker: "ASX:COH",
    quantity: 1,
    price: 4.30,
    fees: 0,
    currency: "AUD",
    platform: "CDIA - Dividends",
    assetClass: "Stock",
    sector: "Healthcare",
    country: "Australia",
    strategy: "Dividend",
    notes: null
  },
  {
    id: "txn_000330",
    source: "initial_excel_import",
    sourceRow: 322,
    date: "2025-04-16",
    action: "Cash Deposit",
    assetTicker: "Cash",
    quantity: 1,
    price: 150.00,
    fees: 0,
    currency: "AUD",
    platform: "Commsec Bank",
    assetClass: "Cash",
    notes: "Sam Thomas"
  },
  {
    id: "txn_000331",
    source: "initial_excel_import",
    sourceRow: 323,
    date: "2025-04-16",
    action: "Cash Dividend",
    assetTicker: "VAS.AX",
    quantity: 1,
    price: 5.00,
    fees: 0,
    currency: "AUD",
    platform: "CDIA - Dividends",
    assetClass: "ETF",
    sector: "ETF",
    country: "Australia",
    strategy: "Dividend",
    notes: null
  },
  {
    id: "txn_000332",
    source: "initial_excel_import",
    sourceRow: 324,
    date: "2025-04-20",
    action: "Cash Deposit",
    assetTicker: "Cash",
    quantity: 1,
    price: 150.00,
    fees: 0,
    currency: "AUD",
    platform: "Commsec Bank",
    assetClass: "Cash",
    notes: "Marc Mario"
  },
  {
    id: "txn_000333",
    source: "initial_excel_import",
    sourceRow: 325,
    date: "2025-04-22",
    action: "Cash Deposit",
    assetTicker: "Cash",
    quantity: 1,
    price: 150.00,
    fees: 0,
    currency: "AUD",
    platform: "Commsec Bank",
    assetClass: "Cash",
    notes: "Tom Flitcroft"
  }
];
