import type { SeedTransaction } from "../types";

export const transactions025: SeedTransaction[] = [
  {
    id: "txn_000244",
    source: "initial_excel_import",
    sourceRow: 236,
    date: "2024-06-01",
    action: "Cash Interest",
    assetTicker: "Interest",
    quantity: 1,
    price: 0.07,
    fees: 0,
    currency: "AUD",
    platform: "CDIA - Dividends",
    assetClass: "Cash",
    sector: "Others",
    country: "Australia",
    strategy: "Dividend",
    notes: null
  },
  {
    id: "txn_000245",
    source: "initial_excel_import",
    sourceRow: 237,
    date: "2024-06-04",
    action: "Cash Deposit",
    assetTicker: "Cash",
    quantity: 1,
    price: 125.00,
    fees: 0,
    currency: "AUD",
    platform: "Commsec Bank",
    assetClass: "Cash",
    notes: "Kieren Chan"
  },
  {
    id: "txn_000246",
    source: "initial_excel_import",
    sourceRow: 238,
    date: "2024-06-05",
    action: "Cash Deposit",
    assetTicker: "Cash",
    quantity: 1,
    price: 500.00,
    fees: 0,
    currency: "AUD",
    platform: "Commsec Bank",
    assetClass: "Cash",
    notes: "Marc Mario"
  },
  {
    id: "txn_000247",
    source: "initial_excel_import",
    sourceRow: 239,
    date: "2024-06-18",
    action: "Cash Deposit",
    assetTicker: "Cash",
    quantity: 1,
    price: 125.00,
    fees: 0,
    currency: "AUD",
    platform: "Commsec Bank",
    assetClass: "Cash",
    notes: "Tom Flitcroft"
  },
  {
    id: "txn_000248",
    source: "initial_excel_import",
    sourceRow: 240,
    date: "2024-06-19",
    action: "Cash Deposit",
    assetTicker: "Cash",
    quantity: 1,
    price: 125.00,
    fees: 0,
    currency: "AUD",
    platform: "Commsec Bank",
    assetClass: "Cash",
    notes: "Sam Thomas"
  },
  {
    id: "txn_000249",
    source: "initial_excel_import",
    sourceRow: 241,
    date: "2024-06-27",
    action: "Cash Withdrawal",
    assetTicker: "Cash",
    quantity: 1,
    price: 500.00,
    fees: 0,
    currency: "AUD",
    platform: "Commsec Bank",
    assetClass: "Cash",
    notes: "Coin Spot"
  },
  {
    id: "txn_000250",
    source: "initial_excel_import",
    sourceRow: 242,
    date: "2024-06-28",
    action: "Buy",
    assetTicker: "SOL-AUD",
    quantity: 2.209164,
    price: 224.08910898,
    fees: 4.95,
    currency: "AUD",
    platform: "Coinbase",
    assetClass: "Crypto",
    sector: "Crypto",
    country: "Crypto World",
    strategy: "High Risk",
    notes: null
  },
  {
    id: "txn_000251",
    source: "initial_excel_import",
    sourceRow: 243,
    date: "2024-06-28",
    action: "Buy",
    assetTicker: "VAS.AX",
    quantity: 6,
    price: 97.44,
    fees: 4.99,
    currency: "AUD",
    platform: "Commsec Shares",
    assetClass: "ETF",
    sector: "ETF",
    country: "Australia",
    strategy: "Low Risk",
    notes: null
  },
  {
    id: "txn_000252",
    source: "initial_excel_import",
    sourceRow: 244,
    date: "2024-06-28",
    action: "Transfer Send",
    assetTicker: "Cash",
    quantity: 1,
    price: 1000.00,
    fees: 0,
    currency: "AUD",
    platform: "Commsec Shares",
    assetClass: "Cash",
    notes: "WDS & VAS Shares"
  },
  {
    id: "txn_000253",
    source: "initial_excel_import",
    sourceRow: 245,
    date: "2024-06-28",
    action: "Cash Dividend",
    assetTicker: "NYSE:LMT",
    quantity: 1,
    price: 3.15,
    fees: 0,
    currency: "AUD",
    platform: "CDIA - Dividends",
    assetClass: "Stock",
    sector: "Others",
    country: "Australia",
    strategy: "Dividend",
    notes: null
  }
];
