import type { SeedTransaction } from "../types";

export const transactions040: SeedTransaction[] = [
  {
    id: "txn_000394",
    source: "initial_excel_import",
    sourceRow: 386,
    date: "2025-09-19",
    action: "Cash Deposit",
    assetTicker: "Cash",
    quantity: 1,
    price: 25.00,
    fees: 0,
    currency: "AUD",
    platform: "Commsec Bank",
    assetClass: "Cash",
    notes: "Tom Flitcroft"
  },
  {
    id: "txn_000395",
    source: "initial_excel_import",
    sourceRow: 387,
    date: "2025-09-19",
    action: "Buy",
    assetTicker: "ASX:COH",
    quantity: 3,
    price: 294.84,
    fees: 4.99,
    currency: "AUD",
    platform: "Commsec Shares",
    assetClass: "Stock",
    sector: "Healthcare",
    country: "Australia",
    strategy: "Dividend",
    notes: "Tom Selected"
  },
  {
    id: "txn_000396",
    source: "initial_excel_import",
    sourceRow: 388,
    date: "2025-09-19",
    action: "Buy",
    assetTicker: "ASX:HPG",
    quantity: 725,
    price: 1.38,
    fees: 4.99,
    currency: "AUD",
    platform: "Commsec Shares",
    assetClass: "Stock",
    sector: "Information Technology",
    country: "Australia",
    strategy: "High Risk",
    notes: "Sam Selected"
  },
  {
    id: "txn_000397",
    source: "initial_excel_import",
    sourceRow: 389,
    date: "2025-09-19",
    action: "Buy",
    assetTicker: "NASDAQ:ADBE",
    quantity: 1.8581,
    price: 352.496,
    fees: 5.00,
    currency: "USD",
    platform: "Commsec International Shares",
    assetClass: "Stock",
    sector: "Information Technology",
    country: "United States",
    strategy: "Medium Risk",
    notes: "Kieren Selected"
  },
  {
    id: "txn_000398",
    source: "initial_excel_import",
    sourceRow: 390,
    date: "2025-09-24",
    action: "Cash Dividend",
    assetTicker: "ASX:WDS",
    quantity: 1,
    price: 28.64,
    fees: 0,
    currency: "AUD",
    platform: "CDIA - Dividends",
    assetClass: "Stock",
    sector: "Energy",
    country: "Australia",
    strategy: "Dividend",
    notes: null
  },
  {
    id: "txn_000399",
    source: "initial_excel_import",
    sourceRow: 391,
    date: "2025-09-25",
    action: "Cash Dividend",
    assetTicker: "ASX:IEL",
    quantity: 1,
    price: 8.00,
    fees: 0,
    currency: "AUD",
    platform: "CDIA - Dividends",
    assetClass: "Stock",
    sector: "Consumer Discretionary",
    country: "Australia",
    strategy: "High Risk",
    notes: null
  },
  {
    id: "txn_000400",
    source: "initial_excel_import",
    sourceRow: 392,
    date: "2025-09-26",
    action: "Cash Dividend",
    assetTicker: "ASX:FMG",
    quantity: 1,
    price: 79.80,
    fees: 0,
    currency: "AUD",
    platform: "CDIA - Dividends",
    assetClass: "Stock",
    sector: "Materials",
    country: "Australia",
    strategy: "Dividend",
    notes: null
  },
  {
    id: "txn_000401",
    source: "initial_excel_import",
    sourceRow: 393,
    date: "2025-10-01",
    action: "Cash Interest",
    assetTicker: "Interest",
    quantity: 1,
    price: 0.02,
    fees: 0,
    currency: "AUD",
    platform: "CDIA - Dividends",
    assetClass: "Cash",
    sector: "Others",
    country: "Australia",
    strategy: "Dividend",
    notes: null
  },
  {
    id: "txn_000402",
    source: "initial_excel_import",
    sourceRow: 394,
    date: "2025-10-13",
    action: "Cash Dividend",
    assetTicker: "ASX:COH",
    quantity: 1,
    price: 4.30,
    fees: 0,
    currency: "AUD",
    platform: "CDIA - Dividends",
    assetClass: "Stock",
    sector: "Healthcare",
    country: "Australia",
    strategy: "Dividend",
    notes: null
  },
  {
    id: "txn_000403",
    source: "initial_excel_import",
    sourceRow: 395,
    date: "2025-10-14",
    action: "Cash Dividend",
    assetTicker: "ASX:EDV",
    quantity: 1,
    price: 24.63,
    fees: 0,
    currency: "AUD",
    platform: "CDIA - Dividends",
    assetClass: "Stock",
    sector: "Consumer Staples",
    country: "Australia",
    strategy: "Dividend",
    notes: null
  }
];
