import { SeedTransaction } from "./transactions-001";

export const seedTransactions002: SeedTransaction[] = [
{
id:"txn_000011",
source:"initial_excel_import",
sourceRow:12,
date:"2021-07-19",
action:"Cash Deposit",
assetTicker:"Cash",
cryptoUrlName:null,
quantity:1,
price:25,
fiatFees:0,
currency:"AUD",
platform:"Commsec Bank",
assetClass:"Cash",
sector:null,
country:null,
strategy:null,
notes:"Kieren Chan",
totalAud:25,
totalFeesIncludedAud:25
},
{
id:"txn_000012",
source:"initial_excel_import",
sourceRow:13,
date:"2021-07-19",
action:"Cash Deposit",
assetTicker:"Cash",
cryptoUrlName:null,
quantity:1,
price:125,
fiatFees:0,
currency:"AUD",
platform:"Commsec Bank",
assetClass:"Cash",
sector:null,
country:null,
strategy:null,
notes:"Sam Thomas",
totalAud:125,
totalFeesIncludedAud:125
},
{
id:"txn_000013",
source:"initial_excel_import",
sourceRow:14,
date:"2021-07-19",
action:"Cash Deposit",
assetTicker:"Cash",
cryptoUrlName:null,
quantity:1,
price:100,
fiatFees:0,
currency:"AUD",
platform:"Commsec Bank",
assetClass:"Cash",
sector:null,
country:null,
strategy:null,
notes:"Tom Flitcroft",
totalAud:100,
totalFeesIncludedAud:100
},
{
id:"txn_000014",
source:"initial_excel_import",
sourceRow:15,
date:"2021-07-19",
action:"Cash Deposit",
assetTicker:"Cash",
cryptoUrlName:null,
quantity:1,
price:25,
fiatFees:0,
currency:"AUD",
platform:"Commsec Bank",
assetClass:"Cash",
sector:null,
country:null,
strategy:null,
notes:"Tom Flitcroft",
totalAud:25,
totalFeesIncludedAud:25
}
];
