export type SeedTransaction = {
  id: string;
  source: "initial_excel_import";
  sourceRow: number;
  date: string;
  action: string;
  assetTicker: string;
  cryptoUrlName: string | null;
  quantity: number;
  price: number;
  fiatFees: number;
  currency: string;
  platform: string;
  assetClass: string;
  sector: string | null;
  country: string | null;
  strategy: string | null;
  notes: string | null;
  totalAud: number;
  totalFeesIncludedAud: number;
};

export const seedTransactions001: SeedTransaction[] = [
  {
    id: "txn_000001",
    source: "initial_excel_import",
    sourceRow: 2,
    date: "2021-05-14",
    action: "Cash Deposit",
    assetTicker: "Cash",
    cryptoUrlName: null,
    quantity: 1,
    price: 350,
    fiatFees: 0,
    currency: "AUD",
    platform: "Commsec Bank",
    assetClass: "Cash",
    sector: null,
    country: null,
    strategy: null,
    notes: "Kieren Chan",
    totalAud: 350,
    totalFeesIncludedAud: 350,
  },
  {
    id: "txn_000002",
    source: "initial_excel_import",
    sourceRow: 3,
    date: "2021-05-14",
    action: "Cash Deposit",
    assetTicker: "Cash",
    cryptoUrlName: null,
    quantity: 1,
    price: 350,
    fiatFees: 0,
    currency: "AUD",
    platform: "Commsec Bank",
    assetClass: "Cash",
    sector: null,
    country: null,
    strategy: null,
    notes: "Sam Thomas",
    totalAud: 350,
    totalFeesIncludedAud: 350,
  },
  {
    id: "txn_000003",
    source: "initial_excel_import",
    sourceRow: 4,
    date: "2021-05-14",
    action: "Cash Deposit",
    assetTicker: "Cash",
    cryptoUrlName: null,
    quantity: 1,
    price: 350,
    fiatFees: 0,
    currency: "AUD",
    platform: "Commsec Bank",
    assetClass: "Cash",
    sector: null,
    country: null,
    strategy: null,
    notes: "Tom Flitcroft",
    totalAud: 350,
    totalFeesIncludedAud: 350,
  },
  {
    id: "txn_000004",
    source: "initial_excel_import",
    sourceRow: 5,
    date: "2021-05-17",
    action: "Cash Deposit",
    assetTicker: "Cash",
    cryptoUrlName: null,
    quantity: 1,
    price: 350,
    fiatFees: 0,
    currency: "AUD",
    platform: "Commsec Bank",
    assetClass: "Cash",
    sector: null,
    country: null,
    strategy: null,
    notes: "Marc Mario",
    totalAud: 350,
    totalFeesIncludedAud: 350,
  },
  {
    id: "txn_000005",
    source: "initial_excel_import",
    sourceRow: 6,
    date: "2021-05-22",
    action: "Cash Deposit",
    assetTicker: "Cash",
    cryptoUrlName: null,
    quantity: 1,
    price: 100,
    fiatFees: 0,
    currency: "AUD",
    platform: "Commsec Bank",
    assetClass: "Cash",
    sector: null,
    country: null,
    strategy: null,
    notes: "Kieren Chan",
    totalAud: 100,
    totalFeesIncludedAud: 100,
  },
  {
    id: "txn_000006",
    source: "initial_excel_import",
    sourceRow: 7,
    date: "2021-06-19",
    action: "Cash Deposit",
    assetTicker: "Cash",
    cryptoUrlName: null,
    quantity: 1,
    price: 100,
    fiatFees: 0,
    currency: "AUD",
    platform: "Commsec Bank",
    assetClass: "Cash",
    sector: null,
    country: null,
    strategy: null,
    notes: "Sam Thomas",
    totalAud: 100,
    totalFeesIncludedAud: 100,
  },
  {
    id: "txn_000007",
    source: "initial_excel_import",
    sourceRow: 8,
    date: "2021-06-22",
    action: "Cash Deposit",
    assetTicker: "Cash",
    cryptoUrlName: null,
    quantity: 1,
    price: 100,
    fiatFees: 0,
    currency: "AUD",
    platform: "Commsec Bank",
    assetClass: "Cash",
    sector: null,
    country: null,
    strategy: null,
    notes: "Marc Mario",
    totalAud: 100,
    totalFeesIncludedAud: 100,
  },
  {
    id: "txn_000008",
    source: "initial_excel_import",
    sourceRow: 9,
    date: "2021-06-22",
    action: "Cash Deposit",
    assetTicker: "Cash",
    cryptoUrlName: null,
    quantity: 1,
    price: 100,
    fiatFees: 0,
    currency: "AUD",
    platform: "Commsec Bank",
    assetClass: "Cash",
    sector: null,
    country: null,
    strategy: null,
    notes: "Tom Flitcroft",
    totalAud: 100,
    totalFeesIncludedAud: 100,
  },
  {
    id: "txn_000009",
    source: "initial_excel_import",
    sourceRow: 10,
    date: "2021-07-15",
    action: "Cash Deposit",
    assetTicker: "Cash",
    cryptoUrlName: null,
    quantity: 1,
    price: 100,
    fiatFees: 0,
    currency: "AUD",
    platform: "Commsec Bank",
    assetClass: "Cash",
    sector: null,
    country: null,
    strategy: null,
    notes: "Kieren Chan",
    totalAud: 100,
    totalFeesIncludedAud: 100,
  },
  {
    id: "txn_000010",
    source: "initial_excel_import",
    sourceRow: 11,
    date: "2021-07-19",
    action: "Cash Deposit",
    assetTicker: "Cash",
    cryptoUrlName: null,
    quantity: 1,
    price: 25,
    fiatFees: 0,
    currency: "AUD",
    platform: "Commsec Bank",
    assetClass: "Cash",
    sector: null,
    country: null,
    strategy: null,
    notes: "Kieren Chan",
    totalAud: 25,
    totalFeesIncludedAud: 25,
  },
];
