import type { WatchlistItem } from "./types";

export const watchlistItems: WatchlistItem[] = [
  {
    id: "1",
    symbol: "AAPL",
    name: "Apple Inc.",
    exchange: "NASDAQ",
    currency: "USD",
    price: 214.6,
    targetPrice: 195,
    changePercent: 1.26,
    marketCap: "3.2T",
    sector: "Technology",
    status: "Watch",
  },
  {
    id: "2",
    symbol: "MSFT",
    name: "Microsoft Corporation",
    exchange: "NASDAQ",
    currency: "USD",
    price: 487.12,
    targetPrice: 430,
    changePercent: 0.88,
    marketCap: "3.6T",
    sector: "Technology",
    status: "Overvalued",
  },
  {
    id: "3",
    symbol: "NDQ",
    name: "Betashares Nasdaq 100 ETF",
    exchange: "ASX",
    currency: "AUD",
    price: 47.88,
    targetPrice: 45,
    changePercent: 1.86,
    marketCap: "ETF",
    sector: "ETF",
    status: "Owned",
  },
  {
    id: "4",
    symbol: "VAS",
    name: "Vanguard Australian Shares ETF",
    exchange: "ASX",
    currency: "AUD",
    price: 97.44,
    targetPrice: 95,
    changePercent: 0.42,
    marketCap: "ETF",
    sector: "ETF",
    status: "Owned",
  },
];
