import type { InvestmentAccount } from "./types";

export const accounts: InvestmentAccount[] = [
  {
    id: "main",
    name: "Main Portfolio",
    broker: "CommSec",
    type: "Brokerage",
    currency: "AUD",
    openingBalance: 58400,
    currentValue: 68420.12,
    investedAmount: 58400,
    cashBalance: 2450.22,
    unrealisedPnl: 10020.12,
    realisedPnl: 2219.8,
    totalReturnPercent: 17.16,
  },
  {
    id: "etf-builder",
    name: "ETF Builder",
    broker: "CommSec Pocket",
    type: "ETF Builder",
    currency: "AUD",
    openingBalance: 26880,
    currentValue: 31860.2,
    investedAmount: 26880,
    cashBalance: 0,
    unrealisedPnl: 4980.2,
    realisedPnl: 0,
    totalReturnPercent: 18.53,
  },
  {
    id: "baby",
    name: "Baby Portfolio",
    broker: "Long Term",
    type: "Long Term",
    currency: "AUD",
    openingBalance: 7140,
    currentValue: 7820.4,
    investedAmount: 7140,
    cashBalance: 0,
    unrealisedPnl: 680.4,
    realisedPnl: 0,
    totalReturnPercent: 9.53,
  },
  {
    id: "cash",
    name: "Cash Reserve",
    broker: "Bank Account",
    type: "Cash",
    currency: "AUD",
    openingBalance: 20320,
    currentValue: 20320,
    investedAmount: 20320,
    cashBalance: 20320,
    unrealisedPnl: 0,
    realisedPnl: 0,
    totalReturnPercent: 0,
  },
];
